#!/usr/bin/env python
# encoding: utf-8

name = "Disproportionation/groups"
shortDesc = ""
longDesc = """
If a birad, reaction site *1 needs to be a triplet.
If a birad, reaction site *3 needs to be a triplet.
If a tri-rad or quad-rad, reaction site *1 and *3 can be anything but singlet.
"""

template(reactants=["Root"], products=["Y_H", "X_R"], ownReverse=False)

reverse = "Molecular_Addition"
reversible = True

reactantNum = 2

productNum = 2

autoGenerated = True

recipe(actions=[
    ['FORM_BOND', '*1', 1, '*4'],
    ['BREAK_BOND', '*2', 1, '*4'],
    ['CHANGE_BOND', '*2', 1, '*3'],
    ['LOSE_RADICAL', '*1', '1'],
    ['LOSE_RADICAL', '*3', '1'],
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1 *2 R!H u0         {2,[S,D,B]} {3,S}
2 *3 R!H u[1,2]     {1,[S,D,B]}
3 *4 H   u0         {1,S}
4 *1 R   u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 1,
    label = "Root_1R!H->C",
    group = 
"""
1 *2 C   u0         {2,[S,D,B]} {3,S}
2 *3 R!H u[1,2]     {1,[S,D,B]}
3 *4 H   u0         {1,S}
4 *1 R   u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 2,
    label = "Root_1R!H->C_Ext-4R-R",
    group = 
"""
1 *2 C   u0         {2,[S,D,B]} {3,S}
2 *3 R!H u[1,2]     {1,[S,D,B]}
3 *4 H   u0         {1,S}
4 *1 R   u[1,2,3,4] {5,[S,D,T,B,Q]}
5    R!H ux         {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 3,
    label = "Root_1R!H->C_Ext-4R-R_Sp-5R!H#4R",
    group = 
"""
1 *2 C u0     {2,[S,D,B]} {3,S}
2 *3 C u[1,2] {1,[S,D,B]}
3 *4 H u0     {1,S}
4 *1 C u1     {5,T}
5    C ux     {4,T}
""",
    kinetics = None,
)

entry(
    index = 4,
    label = "Root_1R!H->C_Ext-4R-R_Sp-5R!H#4R_Ext-1C-R",
    group = 
"""
1 *2 C   u0     {2,[S,D,B]} {3,S} {6,[S,D,T,B,Q]}
2 *3 C   u[1,2] {1,[S,D,B]}
3 *4 H   u0     {1,S}
4 *1 C   u1     {5,T}
5    C   ux     {4,T}
6    R!H ux     {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 5,
    label = "Root_1R!H->C_Ext-4R-R_Sp-5R!H#4R_Ext-1C-R_Ext-1C-R",
    group = 
"""
1 *2 C   u0     {2,[S,D,B]} {3,S} {6,[S,D,T,B,Q]} {7,[S,D,T,B,Q]}
2 *3 C   u[1,2] {1,[S,D,B]}
3 *4 H   u0     r0 {1,S}
4 *1 C   u1     {5,T}
5    C   ux     {4,T}
6    R!H ux     {1,[S,D,T,B,Q]}
7    R!H ux     {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 6,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R",
    group = 
"""
1 *2 C   u0         {2,[S,D,B]} {3,S}
2 *3 R!H u[1,2]     {1,[S,D,B]}
3 *4 H   u0         {1,S}
4 *1 R   u[1,2,3,4] {5,[S,D,Q,B]}
5    R!H ux         {4,[S,D,Q,B]}
""",
    kinetics = None,
)

entry(
    index = 7,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_5R!H->S",
    group = 
"""
1 *2 C u0     {2,S} {3,S}
2 *3 C u[1,2] {1,S}
3 *4 H u0     {1,S}
4 *1 R u1     {5,S}
5    S u0     {4,S}
""",
    kinetics = None,
)

entry(
    index = 8,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_5R!H->S_Ext-2R!H-R",
    group = 
"""
1 *2 C   u0     r0 {2,S} {3,S}
2 *3 C   u[1,2] r0 {1,S} {6,[S,D,T,B,Q]}
3 *4 H   u0     r0 {1,S}
4 *1 R   u1     r0 {5,S}
5    S   u0     r0 {4,S}
6    R!H ux     {2,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 9,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S",
    group = 
"""
1 *2 C     u0         {2,[S,D,B]} {3,S}
2 *3 R!H   u[1,2]     {1,[S,D,B]}
3 *4 H     u0         {1,S}
4 *1 R     u[1,2,3,4] {5,[S,D,Q,B]}
5    [O,C] ux         {4,[S,D,Q,B]}
""",
    kinetics = None,
)

entry(
    index = 10,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0",
    group = 
"""
1 *2 C     u0         {2,[S,D,B]} {3,S}
2 *3 R!H   u[1,2]     {1,[S,D,B]}
3 *4 H     u0         {1,S}
4 *1 R     u[1,2,3,4] {5,[S,D,Q,B]}
5    [O,C] u0         {4,[S,D,Q,B]}
""",
    kinetics = None,
)

entry(
    index = 11,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R",
    group = 
"""
1 *2 C     u0         {2,[S,D,B]} {3,S} {6,[S,D,T,B,Q]}
2 *3 R!H   u[1,2]     {1,[S,D,B]}
3 *4 H     u0         {1,S}
4 *1 R     u[1,2,3,4] {5,[S,D,Q,B]}
5    [O,C] u0         {4,[S,D,Q,B]}
6    C     ux         {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 12,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_Sp-6R!H=1C",
    group = 
"""
1 *2 C u0         {2,[S,D,B]} {3,S} {6,D}
2 *3 C u[1,2]     {1,[S,D,B]}
3 *4 H u0         {1,S}
4 *1 C u[1,2,3,4] {5,[S,D,Q,B]}
5    C u0         {4,[S,D,Q,B]}
6    C ux         {1,D}
""",
    kinetics = None,
)

entry(
    index = 13,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_Sp-6R!H=1C_Sp-5CO-4R",
    group = 
"""
1 *2 C u0     {2,[S,D,B]} {3,S} {6,D}
2 *3 C u[1,2] {1,[S,D,B]}
3 *4 H u0     {1,S}
4 *1 C u1     {5,S}
5    C u0     {4,S}
6    C u0     {1,D}
""",
    kinetics = None,
)

entry(
    index = 14,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_Sp-6R!H=1C_Sp-5CO-4R_Ext-5CO-R",
    group = 
"""
1 *2 C   u0     {2,[S,D,B]} {3,S} {6,D}
2 *3 C   u[1,2] {1,[S,D,B]}
3 *4 H   u0     r0 {1,S}
4 *1 C   u1     {5,S}
5    C   u0     {4,S} {7,[S,D,T,B,Q]}
6    C   u0     {1,D}
7    R!H ux     {5,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 15,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_Sp-6R!H=1C_Sp-5CO-4R_Ext-4R-R",
    group = 
"""
1 *2 C   u0 {2,S} {3,S} {6,D}
2 *3 C   u1 {1,S}
3 *4 H   u0 {1,S}
4 *1 C   u1 {5,S} {7,[S,D,T,B,Q]}
5    C   u0 {4,S}
6    C   u0 {1,D}
7    R!H ux {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 16,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_Sp-6R!H=1C_Sp-5CO-4R_Ext-4R-R_Ext-4R-R",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,S} {6,D}
2 *3 C   u1 r0 {1,S}
3 *4 H   u0 r0 {1,S}
4 *1 C   u1 r0 {5,S} {7,[S,D,T,B,Q]} {8,[S,D,T,B,Q]}
5    C   u0 r0 {4,S}
6    C   u0 r0 {1,D}
7    R!H ux {4,[S,D,T,B,Q]}
8    R!H ux {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 17,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_Sp-6R!H=1C_N-Sp-5CO-4R",
    group = 
"""
1 *2 C u0         r0 {2,S} {3,S} {6,D}
2 *3 C u1         r0 {1,S}
3 *4 H u0         {1,S}
4 *1 C u[1,2,3,4] r0 {5,[B,D]}
5    C u0         r0 {4,[B,D]}
6    C ux         r0 {1,D}
""",
    kinetics = None,
)

entry(
    index = 18,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C",
    group = 
"""
1 *2 C     u0         {2,[S,D,B]} {3,S} {6,[S,T,Q,B]}
2 *3 R!H   u[1,2]     {1,[S,D,B]}
3 *4 H     u0         {1,S}
4 *1 R     u[1,2,3,4] {5,[S,D,Q,B]}
5    [O,C] u0         {4,[S,D,Q,B]}
6    C     ux         {1,[S,T,Q,B]}
""",
    kinetics = None,
)

entry(
    index = 19,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_Ext-1C-R",
    group = 
"""
1 *2 C     u0         {2,[S,D,B]} {3,S} {6,[S,T,Q,B]} {7,[S,D,T,B,Q]}
2 *3 C     u[1,2]     {1,[S,D,B]}
3 *4 H     u0         {1,S}
4 *1 R     u[1,2,3,4] {5,[S,D,Q,B]}
5    [O,C] u0         {4,[S,D,Q,B]}
6    C     ux         {1,[S,T,Q,B]}
7    C     ux         {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 20,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_Ext-1C-R_5CO->O",
    group = 
"""
1 *2 C u0     r0 {2,S} {3,S} {6,S} {7,S}
2 *3 C u[1,2] r0 {1,S}
3 *4 H u0     r0 {1,S}
4 *1 R u1     r0 {5,[S,D,Q,B]}
5    O u0     r0 {4,[S,D,Q,B]}
6    C u0     r0 {1,S}
7    C u0     r0 {1,S}
""",
    kinetics = None,
)

entry(
    index = 21,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_Ext-1C-R_N-5CO->O",
    group = 
"""
1 *2 C u0         {2,[S,D,B]} {3,S} {6,[S,T,Q,B]} {7,[S,D,T,B,Q]}
2 *3 C u[1,2]     {1,[S,D,B]}
3 *4 H u0         {1,S}
4 *1 R u[1,2,3,4] {5,[S,D,Q,B]}
5    C u0         {4,[S,D,Q,B]}
6    C ux         {1,[S,T,Q,B]}
7    C ux         {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 22,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_Ext-1C-R_N-5CO->O_Ext-4R-R",
    group = 
"""
1 *2 C   u0     {2,S} {3,S} {6,S} {7,S}
2 *3 C   u[1,2] {1,S}
3 *4 H   u0     {1,S}
4 *1 C   u1     {5,S} {8,[S,D,T,B,Q]}
5    C   u0     {4,S}
6    C   u0     {1,S}
7    C   u0     {1,S}
8    R!H ux     {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 23,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_Ext-1C-R_N-5CO->O_Ext-4R-R_Ext-4R-R",
    group = 
"""
1 *2 C   u0     r0 {2,S} {3,S} {6,S} {7,S}
2 *3 C   u[1,2] r0 {1,S}
3 *4 H   u0     r0 {1,S}
4 *1 C   u1     r0 {5,S} {8,[S,D,T,B,Q]} {9,[S,D,T,B,Q]}
5    C   u0     r0 {4,S}
6    C   u0     r0 {1,S}
7    C   u0     r0 {1,S}
8    R!H ux     {4,[S,D,T,B,Q]}
9    R!H ux     {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 24,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_Ext-1C-R_N-5CO->O_Sp-5C-4R",
    group = 
"""
1 *2 C u0         {2,[S,D,B]} {3,S} {6,[S,T,Q,B]} {7,[S,D,T,B,Q]}
2 *3 C u[1,2]     {1,[S,D,B]}
3 *4 H u0         {1,S}
4 *1 R u[1,2,3,4] {5,S}
5    C u0         {4,S}
6    C ux         {1,[S,T,Q,B]}
7    C ux         {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 25,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_Ext-1C-R_N-5CO->O_Sp-5C-4R_Ext-5C-R",
    group = 
"""
1 *2 C u0         {2,[S,D,B]} {3,S} {6,[S,T,Q,B]} {7,[S,D,T,B,Q]}
2 *3 C u[1,2]     {1,[S,D,B]}
3 *4 H u0         {1,S}
4 *1 R u[1,2,3,4] {5,S}
5    C u0         {4,S} {8,D}
6    C ux         {1,[S,T,Q,B]}
7    C ux         {1,[S,D,T,B,Q]}
8    C u0         {5,D}
""",
    kinetics = None,
)

entry(
    index = 26,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_Ext-1C-R_N-5CO->O_Sp-5C-4R_Ext-5C-R_4R->C",
    group = 
"""
1 *2 C u0         {2,[S,D,B]} {3,S} {6,[S,T,Q,B]} {7,[S,D,T,B,Q]}
2 *3 C u[1,2]     {1,[S,D,B]}
3 *4 H u0         {1,S}
4 *1 C u[1,2,3,4] {5,S}
5    C u0         {4,S} {8,D}
6    C ux         {1,[S,T,Q,B]}
7    C ux         {1,[S,D,T,B,Q]}
8    C u0         r0 {5,D}
""",
    kinetics = None,
)

entry(
    index = 27,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_Ext-1C-R_N-5CO->O_Sp-5C-4R_Ext-5C-R_N-4R->C",
    group = 
"""
1 *2 C u0         {2,[S,D,B]} {3,S} {6,[S,T,Q,B]} {7,[S,D,T,B,Q]}
2 *3 C u[1,2]     {1,[S,D,B]}
3 *4 H u0         {1,S}
4 *1 S u[1,2,3,4] {5,S}
5    C u0         {4,S} {8,D}
6    C ux         {1,[S,T,Q,B]}
7    C ux         {1,[S,D,T,B,Q]}
8    C u0         r0 {5,D}
""",
    kinetics = None,
)

entry(
    index = 28,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_Ext-1C-R_N-5CO->O_Sp-5C-4R_4R->C",
    group = 
"""
1 *2 C u0         {2,[S,D,B]} {3,S} {6,[S,T,Q,B]} {7,[S,D,T,B,Q]}
2 *3 C u[1,2]     {1,[S,D,B]}
3 *4 H u0         {1,S}
4 *1 C u[1,2,3,4] {5,S}
5    C u0         {4,S}
6    C ux         {1,[S,T,Q,B]}
7    C ux         {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 29,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_Ext-1C-R_N-5CO->O_Sp-5C-4R_N-4R->C",
    group = 
"""
1 *2 C u0         {2,[S,D,B]} {3,S} {6,[S,T,Q,B]} {7,[S,D,T,B,Q]}
2 *3 C u[1,2]     {1,[S,D,B]}
3 *4 H u0         {1,S}
4 *1 S u[1,2,3,4] {5,S}
5    C u0         {4,S}
6    C ux         {1,[S,T,Q,B]}
7    C ux         {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 30,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_Ext-1C-R_N-5CO->O_N-Sp-5C-4R",
    group = 
"""
1 *2 C u0         {2,[S,D,B]} {3,S} {6,[S,T,Q,B]} {7,[S,D,T,B,Q]}
2 *3 C u[1,2]     {1,[S,D,B]}
3 *4 H u0         {1,S}
4 *1 R u[1,2,3,4] {5,D}
5    C u0         {4,D}
6    C ux         {1,[S,T,Q,B]}
7    C ux         {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 31,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_4R->C",
    group = 
"""
1 *2 C     u0         {2,[S,D,B]} {3,S} {6,[S,T,Q,B]}
2 *3 R!H   u[1,2]     {1,[S,D,B]}
3 *4 H     u0         {1,S}
4 *1 C     u[1,2,3,4] {5,[S,D,Q,B]}
5    [O,C] u0         {4,[S,D,Q,B]}
6    C     ux         {1,[S,T,Q,B]}
""",
    kinetics = None,
)

entry(
    index = 32,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_4R->C_Sp-5CCOO=4C",
    group = 
"""
1 *2 C     u0 {2,[S,D,B]} {3,S} {6,[S,T,Q,B]}
2 *3 R!H   u1 {1,[S,D,B]}
3 *4 H     u0 r0 {1,S}
4 *1 C     u1 {5,D}
5    [O,C] u0 {4,D}
6    C     u0 {1,[S,T,Q,B]}
""",
    kinetics = None,
)

entry(
    index = 33,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_4R->C_N-Sp-5CCOO=4C",
    group = 
"""
1 *2 C     u0         {2,[S,D,B]} {3,S} {6,[S,T,Q,B]}
2 *3 R!H   u[1,2]     {1,[S,D,B]}
3 *4 H     u0         {1,S}
4 *1 C     u[1,2,3,4] {5,[S,B]}
5    [O,C] u0         {4,[S,B]}
6    C     ux         {1,[S,T,Q,B]}
""",
    kinetics = None,
)

entry(
    index = 34,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_4R->C_N-Sp-5CCOO=4C_2R!H->C",
    group = 
"""
1 *2 C     u0         {2,[S,D,B]} {3,S} {6,[S,T,Q,B]}
2 *3 C     u[1,2]     {1,[S,D,B]}
3 *4 H     u0         {1,S}
4 *1 C     u[1,2,3,4] {5,[S,B]}
5    [O,C] u0         {4,[S,B]}
6    C     ux         {1,[S,T,Q,B]}
""",
    kinetics = None,
)

entry(
    index = 35,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_4R->C_N-Sp-5CCOO=4C_2R!H->C_5CO->O",
    group = 
"""
1 *2 C u0 {2,[S,D,B]} {3,S} {6,[S,T,Q,B]}
2 *3 C u1 {1,[S,D,B]}
3 *4 H u0 r0 {1,S}
4 *1 C u1 {5,[S,B]}
5    O u0 {4,[S,B]}
6    C u0 {1,[S,T,Q,B]}
""",
    kinetics = None,
)

entry(
    index = 36,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_4R->C_N-Sp-5CCOO=4C_2R!H->C_N-5CO->O",
    group = 
"""
1 *2 C u0         {2,[S,D,B]} {3,S} {6,[S,T,Q,B]}
2 *3 C u[1,2]     {1,[S,D,B]}
3 *4 H u0         {1,S}
4 *1 C u[1,2,3,4] {5,[S,B]}
5    C u0         {4,[S,B]}
6    C ux         {1,[S,T,Q,B]}
""",
    kinetics = None,
)

entry(
    index = 37,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_4R->C_N-Sp-5CCOO=4C_2R!H->C_N-5CO->O_Ext-4C-R",
    group = 
"""
1 *2 C   u0         {2,[S,D,B]} {3,S} {6,[S,T,Q,B]}
2 *3 C   u[1,2]     {1,[S,D,B]}
3 *4 H   u0         {1,S}
4 *1 C   u[1,2,3,4] {5,[S,B]} {7,[S,D,T,B,Q]}
5    C   u0         {4,[S,B]}
6    C   ux         {1,[S,T,Q,B]}
7    R!H ux         {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 38,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_4R->C_N-Sp-5CCOO=4C_2R!H->C_N-5CO->O_Ext-4C-R_1C-inRing",
    group = 
"""
1 *2 C u0 r1 {2,[S,D,B]} {3,S} {6,[S,T,Q,B]}
2 *3 C u1 {1,[S,D,B]}
3 *4 H u0 r0 {1,S}
4 *1 C u1 {5,[S,B]} {7,[S,D,T,B,Q]}
5    C u0 {4,[S,B]}
6    C u0 {1,[S,T,Q,B]}
7    C u0 {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 39,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_4R->C_N-Sp-5CCOO=4C_2R!H->C_N-5CO->O_Ext-4C-R_N-1C-inRing",
    group = 
"""
1 *2 C   u0         r0 {2,S} {3,S} {6,S}
2 *3 C   u[1,2]     {1,S}
3 *4 H   u0         {1,S}
4 *1 C   u[1,2,3,4] {5,S} {7,[S,D,T,B,Q]}
5    C   u0         {4,S}
6    C   ux         {1,S}
7    R!H ux         {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 40,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_4R->C_N-Sp-5CCOO=4C_2R!H->C_N-5CO->O_Ext-4C-R_N-1C-inRing_Ext-4C-R",
    group = 
"""
1 *2 C   u0         r0 {2,S} {3,S} {6,S}
2 *3 C   u[1,2]     r0 {1,S}
3 *4 H   u0         {1,S}
4 *1 C   u[1,2,3,4] r0 {5,S} {7,[S,D,T,B,Q]} {8,[S,D,T,B,Q]}
5    C   u0         r0 {4,S}
6    C   ux         r0 {1,S}
7    R!H ux         {4,[S,D,T,B,Q]}
8    R!H ux         {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 41,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_4R->C_N-Sp-5CCOO=4C_2R!H->C_N-5CO->O_Ext-5C-R",
    group = 
"""
1 *2 C   u0         r0 {2,S} {3,S} {6,S}
2 *3 C   u[1,2]     r0 {1,S}
3 *4 H   u0         {1,S}
4 *1 C   u[1,2,3,4] r0 {5,S}
5    C   u0         r0 {4,S} {7,[S,D,T,B,Q]}
6    C   ux         r0 {1,S}
7    R!H ux         {5,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 42,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_4R->C_N-Sp-5CCOO=4C_N-2R!H->C",
    group = 
"""
1 *2 C u0 {2,S} {3,S} {6,S}
2 *3 S u1 {1,S}
3 *4 H u0 {1,S}
4 *1 C u1 {5,S}
5    C u0 {4,S}
6    C u0 {1,S}
""",
    kinetics = None,
)

entry(
    index = 43,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_4R->C_N-Sp-5CCOO=4C_N-2R!H->C_Ext-5CO-R_Ext-4C-R_Ext-7R!H-R_Ext-5CO-R",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,S} {6,S}
2 *3 S   u1 r0 {1,S}
3 *4 H   u0 r0 {1,S}
4 *1 C   u1 r0 {5,S} {7,[S,D,T,B,Q]}
5    C   u0 r0 {4,S} {9,[S,D,T,B,Q]}
6    C   u0 r0 {1,S}
7    C   ux {4,[S,D,T,B,Q]} {8,D}
8    C   u0 r0 {7,D}
9    R!H ux {5,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 44,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_N-4R->C",
    group = 
"""
1 *2 C     u0         {2,[S,D,B]} {3,S} {6,[S,T,Q,B]}
2 *3 R!H   u[1,2]     {1,[S,D,B]}
3 *4 H     u0         {1,S}
4 *1 S     u[1,2,3,4] {5,[S,D,Q,B]}
5    [O,C] u0         {4,[S,D,Q,B]}
6    C     ux         {1,[S,T,Q,B]}
""",
    kinetics = None,
)

entry(
    index = 45,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-4R-R",
    group = 
"""
1 *2 C   u0         {2,[S,D,B]} {3,S}
2 *3 C   u[1,2]     {1,[S,D,B]}
3 *4 H   u0         {1,S}
4 *1 C   u[1,2,3,4] {5,[S,D,Q,B]} {6,[S,D,T,B,Q]}
5    C   u0         {4,[S,D,Q,B]}
6    R!H ux         {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 46,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-4R-R_Ext-2R!H-R",
    group = 
"""
1 *2 C   u0 {2,S} {3,S}
2 *3 C   u1 {1,S} {7,[S,D,T,B,Q]}
3 *4 H   u0 r0 {1,S}
4 *1 C   u1 {5,S} {6,S}
5    C   u0 {4,S}
6    C   u0 r0 {4,S}
7    R!H ux {2,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 47,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-4R-R_Ext-4R-R",
    group = 
"""
1 *2 C   u0         {2,[S,D,B]} {3,S}
2 *3 C   u[1,2]     {1,[S,D,B]}
3 *4 H   u0         {1,S}
4 *1 C   u[1,2,3,4] {5,[S,D,Q,B]} {6,[S,D,T,B,Q]} {7,[S,D,T,B,Q]}
5    C   u0         {4,[S,D,Q,B]}
6    R!H ux         {4,[S,D,T,B,Q]}
7    R!H ux         {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 48,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_2R!H->S",
    group = 
"""
1 *2 C     u0         r0 {2,[S,D,B]} {3,S}
2 *3 S     u[1,2]     r0 {1,[S,D,B]}
3 *4 H     u0         {1,S}
4 *1 R     u[1,2,3,4] r0 {5,[S,D,Q,B]}
5    [O,C] u0         r0 {4,[S,D,Q,B]}
""",
    kinetics = None,
)

entry(
    index = 49,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_N-2R!H->S",
    group = 
"""
1 *2 C     u0 {2,[S,D,B]} {3,S}
2 *3 [N,C] u1 {1,[S,D,B]}
3 *4 H     u0 {1,S}
4 *1 R     u1 {5,[S,D,Q,B]}
5    [O,C] u0 {4,[S,D,Q,B]}
""",
    kinetics = None,
)

entry(
    index = 50,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_N-2R!H->S_Sp-5CO-4R",
    group = 
"""
1 *2 C     u0 {2,[S,D,B]} {3,S}
2 *3 [N,C] u1 {1,[S,D,B]}
3 *4 H     u0 {1,S}
4 *1 R     u1 {5,S}
5    [O,C] u0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 51,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_N-2R!H->S_Sp-5CO-4R_5CO->O",
    group = 
"""
1 *2 C     u0 {2,[S,D,B]} {3,S}
2 *3 [N,C] u1 {1,[S,D,B]}
3 *4 H     u0 {1,S}
4 *1 R     u1 {5,S}
5    O     u0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 52,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_N-2R!H->S_Sp-5CO-4R_5CO->O_2CN->N",
    group = 
"""
1 *2 C u0 {2,[S,D,B]} {3,S}
2 *3 N u1 {1,[S,D,B]}
3 *4 H u0 r0 {1,S}
4 *1 R u1 {5,S}
5    O u0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 53,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_N-2R!H->S_Sp-5CO-4R_5CO->O_N-2CN->N",
    group = 
"""
1 *2 C u0 {2,[S,D,B]} {3,S}
2 *3 C u1 {1,[S,D,B]}
3 *4 H u0 r0 {1,S}
4 *1 R u1 {5,S}
5    O u0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 54,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_N-2R!H->S_Sp-5CO-4R_N-5CO->O",
    group = 
"""
1 *2 C u0 {2,S} {3,S}
2 *3 C u1 {1,S}
3 *4 H u0 {1,S}
4 *1 C u1 {5,S}
5    C u0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 55,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_N-2R!H->S_Sp-5CO-4R_N-5CO->O_Ext-5C-R",
    group = 
"""
1 *2 C   u0 {2,S} {3,S}
2 *3 C   u1 {1,S}
3 *4 H   u0 r0 {1,S}
4 *1 C   u1 {5,S}
5    C   u0 {4,S} {6,[S,D,T,B,Q]}
6    R!H ux {5,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 56,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_N-2R!H->S_N-Sp-5CO-4R",
    group = 
"""
1 *2 C     u0 {2,[S,D,B]} {3,S}
2 *3 [N,C] u1 {1,[S,D,B]}
3 *4 H     u0 r0 {1,S}
4 *1 R     u1 {5,D}
5    [O,C] u0 {4,D}
""",
    kinetics = None,
)

entry(
    index = 57,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_N-5CO-u0",
    group = 
"""
1 *2 C u0         {2,[S,D,B]} {3,S}
2 *3 C u[1,2]     {1,[S,D,B]}
3 *4 H u0         {1,S}
4 *1 O u[1,2,3,4] {5,[S,D,Q,B]}
5    O u1         {4,[S,D,Q,B]}
""",
    kinetics = None,
)

entry(
    index = 58,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_N-5CO-u0_Ext-2R!H-R",
    group = 
"""
1 *2 C   u0         r0 {2,[S,D,B]} {3,S}
2 *3 C   u1         r0 {1,[S,D,B]} {6,[S,D,T,B,Q]}
3 *4 H   u0         {1,S}
4 *1 O   u[1,2,3,4] r0 {5,S}
5    O   u1         r0 {4,S}
6    R!H ux         {2,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 59,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_N-5CO-u0_Ext-1C-R",
    group = 
"""
1 *2 C u0         {2,[S,D,B]} {3,S} {6,[S,D,T,B,Q]}
2 *3 C u[1,2]     {1,[S,D,B]}
3 *4 H u0         {1,S}
4 *1 O u[1,2,3,4] {5,[S,D,Q,B]}
5    O u1         {4,[S,D,Q,B]}
6    C ux         {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 60,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_N-5CO-u0_Ext-1C-R_Sp-6R!H-1C",
    group = 
"""
1 *2 C u0         {2,[S,D,B]} {3,S} {6,S}
2 *3 C u[1,2]     {1,[S,D,B]}
3 *4 H u0         {1,S}
4 *1 O u[1,2,3,4] {5,[S,D,Q,B]}
5    O u1         {4,[S,D,Q,B]}
6    C ux         {1,S}
""",
    kinetics = None,
)

entry(
    index = 61,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_N-5CO-u0_Ext-1C-R_Sp-6R!H-1C_Ext-1C-R",
    group = 
"""
1 *2 C u0         {2,[S,D,B]} {3,S} {6,S} {7,[S,D,T,B,Q]}
2 *3 C u[1,2]     {1,[S,D,B]}
3 *4 H u0         {1,S}
4 *1 O u[1,2,3,4] {5,[S,D,Q,B]}
5    O u1         {4,[S,D,Q,B]}
6    C ux         {1,S}
7    C ux         {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 62,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_N-5CO-u0_Ext-1C-R_Sp-6R!H-1C_Ext-1C-R_Ext-6R!H-R",
    group = 
"""
1 *2 C u0         {2,[S,D,B]} {3,S} {6,S} {7,[S,D,T,B,Q]}
2 *3 C u[1,2]     {1,[S,D,B]}
3 *4 H u0         {1,S}
4 *1 O u[1,2,3,4] {5,[S,D,Q,B]}
5    O u1         {4,[S,D,Q,B]}
6    C ux         {1,S} {8,D}
7    C ux         {1,[S,D,T,B,Q]}
8    C u0         {6,D}
""",
    kinetics = None,
)

entry(
    index = 63,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_N-5CO-u0_Ext-1C-R_Sp-6R!H-1C_Ext-1C-R_Ext-6R!H-R_Ext-7R!H-R",
    group = 
"""
1 *2 C   u0         {2,[S,D,B]} {3,S} {6,S} {7,[S,D,T,B,Q]}
2 *3 C   u[1,2]     {1,[S,D,B]}
3 *4 H   u0         {1,S}
4 *1 O   u[1,2,3,4] {5,[S,D,Q,B]}
5    O   u1         {4,[S,D,Q,B]}
6    C   ux         {1,S} {8,D}
7    C   ux         {1,[S,D,T,B,Q]} {9,[S,D,T,B,Q]}
8    C   u0         r0 {6,D}
9    R!H ux         {7,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 64,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_N-5CO-u0_Ext-1C-R_Sp-6R!H-1C_Ext-6R!H-R",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,S} {6,S}
2 *3 C u1 r0 {1,S}
3 *4 H u0 r0 {1,S}
4 *1 O u1 r0 {5,S}
5    O u1 r0 {4,S}
6    C u0 r0 {1,S} {7,D}
7    C u0 r0 {6,D}
""",
    kinetics = None,
)

entry(
    index = 65,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_N-5CO-u0_Ext-1C-R_N-Sp-6R!H-1C",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,S} {6,[B,D,T,Q]}
2 *3 C u1 r0 {1,S}
3 *4 H u0 r0 {1,S}
4 *1 O u1 r0 {5,S}
5    O u1 r0 {4,S}
6    C u0 r0 {1,[B,D,T,Q]}
""",
    kinetics = None,
)

entry(
    index = 66,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_N-5CO-u0_Sp-2R!H-1C",
    group = 
"""
1 *2 C u0         {2,S} {3,S}
2 *3 C u[1,2]     {1,S}
3 *4 H u0         {1,S}
4 *1 O u[1,2,3,4] {5,[S,D,Q,B]}
5    O u1         {4,[S,D,Q,B]}
""",
    kinetics = None,
)

entry(
    index = 67,
    label = "Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_N-5CO-u0_N-Sp-2R!H-1C",
    group = 
"""
1 *2 C u0         {2,D} {3,S}
2 *3 C u[1,2]     {1,D}
3 *4 H u0         {1,S}
4 *1 O u[1,2,3,4] {5,[S,D,Q,B]}
5    O u1         {4,[S,D,Q,B]}
""",
    kinetics = None,
)

entry(
    index = 68,
    label = "Root_1R!H->C_2R!H->C",
    group = 
"""
1 *2 C u0         {2,[S,D,B]} {3,S}
2 *3 C u[1,2]     {1,[S,D,B]}
3 *4 H u0         {1,S}
4 *1 R u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 69,
    label = "Root_1R!H->C_2R!H->C_4R->O",
    group = 
"""
1 *2 C u0         {2,[S,D,B]} {3,S}
2 *3 C u[1,2]     {1,[S,D,B]}
3 *4 H u0         {1,S}
4 *1 O u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 70,
    label = "Root_1R!H->C_2R!H->C_4R->O_Ext-1C-R",
    group = 
"""
1 *2 C u0         {2,[S,D,B]} {3,S} {5,[S,D,T,B,Q]}
2 *3 C u[1,2]     {1,[S,D,B]}
3 *4 H u0         {1,S}
4 *1 O u[1,2,3,4]
5    C ux         {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 71,
    label = "Root_1R!H->C_2R!H->C_4R->O_Ext-1C-R_Sp-5R!H-1C",
    group = 
"""
1 *2 C u0     {2,[S,D,B]} {3,S} {5,S}
2 *3 C u[1,2] {1,[S,D,B]}
3 *4 H u0     {1,S}
4 *1 O u1    
5    C ux     {1,S}
""",
    kinetics = None,
)

entry(
    index = 72,
    label = "Root_1R!H->C_2R!H->C_4R->O_Ext-1C-R_Sp-5R!H-1C_Ext-1C-R",
    group = 
"""
1 *2 C   u0     r0 {2,[S,D,B]} {3,S} {5,S} {6,[S,D,T,B,Q]}
2 *3 C   u[1,2] r0 {1,[S,D,B]}
3 *4 H   u0     {1,S}
4 *1 O   u1     r0
5    C   ux     {1,S}
6    R!H ux     {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 73,
    label = "Root_1R!H->C_2R!H->C_4R->O_Ext-1C-R_N-Sp-5R!H-1C",
    group = 
"""
1 *2 C u0         {2,S} {3,S} {5,[B,D,T,Q]}
2 *3 C u1         {1,S}
3 *4 H u0         r0 {1,S}
4 *1 O u[1,2,3,4]
5    C u0         r0 {1,[B,D,T,Q]}
""",
    kinetics = None,
)

entry(
    index = 74,
    label = "Root_1R!H->C_2R!H->C_N-4R->O",
    group = 
"""
1 *2 C       u0         {2,[S,D,B]} {3,S}
2 *3 C       u[1,2]     {1,[S,D,B]}
3 *4 H       u0         {1,S}
4 *1 [N,H,C] u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 75,
    label = "Root_1R!H->C_2R!H->C_N-4R->O_4CHN->H",
    group = 
"""
1 *2 C u0         {2,[S,D,B]} {3,S}
2 *3 C u[1,2]     {1,[S,D,B]}
3 *4 H u0         {1,S}
4 *1 H u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 76,
    label = "Root_1R!H->C_2R!H->C_N-4R->O_4CHN->H_Ext-1C-R",
    group = 
"""
1 *2 C   u0         {2,[S,D,B]} {3,S} {5,[S,D,T,B,Q]}
2 *3 C   u[1,2]     {1,[S,D,B]}
3 *4 H   u0         {1,S}
4 *1 H   u[1,2,3,4]
5    R!H ux         {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 77,
    label = "Root_1R!H->C_2R!H->C_N-4R->O_4CHN->H_Ext-1C-R_Ext-1C-R",
    group = 
"""
1 *2 C   u0         r0 {2,[S,D,B]} {3,S} {5,[S,D,T,B,Q]} {6,[S,D,T,B,Q]}
2 *3 C   u[1,2]     r0 {1,[S,D,B]}
3 *4 H   u0         {1,S}
4 *1 H   u[1,2,3,4] r0
5    R!H ux         {1,[S,D,T,B,Q]}
6    R!H ux         {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 78,
    label = "Root_1R!H->C_2R!H->C_N-4R->O_N-4CHN->H",
    group = 
"""
1 *2 C u0         {2,[S,D,B]} {3,S}
2 *3 C u[1,2]     {1,[S,D,B]}
3 *4 H u0         {1,S}
4 *1 C u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 79,
    label = "Root_1R!H->C_2R!H->C_N-4R->O_N-4CHN->H_Ext-1C-R",
    group = 
"""
1 *2 C   u0         {2,[S,D,B]} {3,S} {5,[S,D,T,B,Q]}
2 *3 C   u[1,2]     {1,[S,D,B]}
3 *4 H   u0         {1,S}
4 *1 C   u[1,2,3,4]
5    R!H ux         {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 80,
    label = "Root_1R!H->C_2R!H->C_N-4R->O_N-4CHN->H_Ext-1C-R_Ext-1C-R",
    group = 
"""
1 *2 C   u0         r0 {2,[S,D,B]} {3,S} {5,[S,D,T,B,Q]} {6,[S,D,T,B,Q]}
2 *3 C   u[1,2]     r0 {1,[S,D,B]}
3 *4 H   u0         {1,S}
4 *1 C   u[1,2,3,4] r0
5    R!H ux         {1,[S,D,T,B,Q]}
6    R!H ux         {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 81,
    label = "Root_1R!H->C_2R!H->C_N-4R->O_N-4CHN->H_Ext-1C-R_Sp-5R!H-1C",
    group = 
"""
1 *2 C u0         {2,S} {3,S} {5,S}
2 *3 C u1         {1,S}
3 *4 H u0         {1,S}
4 *1 C u[1,2,3,4]
5    C u0         {1,S}
""",
    kinetics = None,
)

entry(
    index = 82,
    label = "Root_1R!H->C_2R!H->C_N-4R->O_N-4CHN->H_Ext-1C-R_Sp-5R!H-1C_4C-u1",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,S} {5,S}
2 *3 C u1 r0 {1,S}
3 *4 H u0 r0 {1,S}
4 *1 C u1 r0
5    C u0 r0 {1,S}
""",
    kinetics = None,
)

entry(
    index = 83,
    label = "Root_1R!H->C_2R!H->C_N-4R->O_N-4CHN->H_Ext-1C-R_Sp-5R!H-1C_N-4C-u1",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,S} {5,S}
2 *3 C u1 r0 {1,S}
3 *4 H u0 r0 {1,S}
4 *1 C u2 r0
5    C u0 r0 {1,S}
""",
    kinetics = None,
)

entry(
    index = 84,
    label = "Root_1R!H->C_2R!H->C_N-4R->O_N-4CHN->H_Ext-1C-R_N-Sp-5R!H-1C",
    group = 
"""
1 *2 C u0         {2,[S,D,B]} {3,S} {5,D}
2 *3 C u[1,2]     {1,[S,D,B]}
3 *4 H u0         {1,S}
4 *1 C u[1,2,3,4]
5    C ux         {1,D}
""",
    kinetics = None,
)

entry(
    index = 85,
    label = "Root_1R!H->C_2R!H->C_N-4R->O_N-4CHN->H_4C-u1",
    group = 
"""
1 *2 C u0     {2,[S,D,B]} {3,S}
2 *3 C u[1,2] {1,[S,D,B]}
3 *4 H u0     {1,S}
4 *1 C u1    
""",
    kinetics = None,
)

entry(
    index = 86,
    label = "Root_1R!H->C_2R!H->C_N-4R->O_N-4CHN->H_N-4C-u1",
    group = 
"""
1 *2 C u0     {2,[S,D,B]} {3,S}
2 *3 C u[1,2] {1,[S,D,B]}
3 *4 H u0     {1,S}
4 *1 C u2    
""",
    kinetics = None,
)

entry(
    index = 87,
    label = "Root_1R!H->C_N-2R!H->C",
    group = 
"""
1 *2 C       u0         {2,[S,D,B]} {3,S}
2 *3 [N,O,S] u[1,2]     {1,[S,D,B]}
3 *4 H       u0         {1,S}
4 *1 R       u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 88,
    label = "Root_1R!H->C_N-2R!H->C_4R->H",
    group = 
"""
1 *2 C       u0         {2,[S,D,B]} {3,S}
2 *3 [N,O,S] u[1,2]     {1,[S,D,B]}
3 *4 H       u0         {1,S}
4 *1 H       u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 89,
    label = "Root_1R!H->C_N-2R!H->C_4R->H_Ext-2NOS-R",
    group = 
"""
1 *2 C       u0     r0 {2,[S,D,B]} {3,S}
2 *3 [N,O,S] u[1,2] r0 {1,[S,D,B]} {5,[S,D,T,B,Q]}
3 *4 H       u0     {1,S}
4 *1 H       u1     r0
5    R!H     ux     {2,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 90,
    label = "Root_1R!H->C_N-2R!H->C_4R->H_Sp-2NOS-1C",
    group = 
"""
1 *2 C       u0 {2,S} {3,S}
2 *3 [N,O,S] u1 {1,S}
3 *4 H       u0 {1,S}
4 *1 H       u1
""",
    kinetics = None,
)

entry(
    index = 91,
    label = "Root_1R!H->C_N-2R!H->C_4R->H_Sp-2NOS-1C_2NOS->N",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,S}
2 *3 N u1 r0 {1,S}
3 *4 H u0 r0 {1,S}
4 *1 H u1 r0
""",
    kinetics = None,
)

entry(
    index = 92,
    label = "Root_1R!H->C_N-2R!H->C_4R->H_Sp-2NOS-1C_N-2NOS->N",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,S}
2 *3 O u1 r0 {1,S}
3 *4 H u0 r0 {1,S}
4 *1 H u1 r0
""",
    kinetics = None,
)

entry(
    index = 93,
    label = "Root_1R!H->C_N-2R!H->C_4R->H_N-Sp-2NOS-1C",
    group = 
"""
1 *2 C       u0         {2,D} {3,S}
2 *3 [N,O,S] u[1,2]     {1,D}
3 *4 H       u0         {1,S}
4 *1 H       u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 94,
    label = "Root_1R!H->C_N-2R!H->C_N-4R->H",
    group = 
"""
1 *2 C       u0         {2,[S,D,B]} {3,S}
2 *3 N       u[1,2]     {1,[S,D,B]}
3 *4 H       u0         {1,S}
4 *1 [N,C,O] u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 95,
    label = "Root_1R!H->C_N-2R!H->C_N-4R->H_4CNO->O",
    group = 
"""
1 *2 C u0         {2,[S,D,B]} {3,S}
2 *3 N u[1,2]     {1,[S,D,B]}
3 *4 H u0         {1,S}
4 *1 O u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 96,
    label = "Root_1R!H->C_N-2R!H->C_N-4R->H_4CNO->O_4O-u1",
    group = 
"""
1 *2 C u0     {2,[S,D,B]} {3,S}
2 *3 N u[1,2] {1,[S,D,B]}
3 *4 H u0     {1,S}
4 *1 O u1    
""",
    kinetics = None,
)

entry(
    index = 97,
    label = "Root_1R!H->C_N-2R!H->C_N-4R->H_4CNO->O_4O-u1_Sp-2NOS-1C",
    group = 
"""
1 *2 C u0     r0 {2,S} {3,S}
2 *3 N u[1,2] r0 {1,S}
3 *4 H u0     {1,S}
4 *1 O u1     r0
""",
    kinetics = None,
)

entry(
    index = 98,
    label = "Root_1R!H->C_N-2R!H->C_N-4R->H_4CNO->O_4O-u1_N-Sp-2NOS-1C",
    group = 
"""
1 *2 C u0 {2,D} {3,S}
2 *3 N u1 {1,D}
3 *4 H u0 {1,S}
4 *1 O u1
""",
    kinetics = None,
)

entry(
    index = 99,
    label = "Root_1R!H->C_N-2R!H->C_N-4R->H_4CNO->O_4O-u1_N-Sp-2NOS-1C_Ext-2NOS-R",
    group = 
"""
1 *2 C   u0 {2,D} {3,S}
2 *3 N   u1 {1,D} {5,[S,D,T,B,Q]}
3 *4 H   u0 r0 {1,S}
4 *1 O   u1
5    R!H ux {2,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 100,
    label = "Root_1R!H->C_N-2R!H->C_N-4R->H_4CNO->O_N-4O-u1",
    group = 
"""
1 *2 C u0     {2,[S,D,B]} {3,S}
2 *3 N u[1,2] {1,[S,D,B]}
3 *4 H u0     {1,S}
4 *1 O u2    
""",
    kinetics = None,
)

entry(
    index = 101,
    label = "Root_1R!H->C_N-2R!H->C_N-4R->H_4CNO->O_N-4O-u1_Sp-2NOS-1C",
    group = 
"""
1 *2 C u0     r0 {2,S} {3,S}
2 *3 N u[1,2] r0 {1,S}
3 *4 H u0     {1,S}
4 *1 O u2     r0
""",
    kinetics = None,
)

entry(
    index = 102,
    label = "Root_1R!H->C_N-2R!H->C_N-4R->H_4CNO->O_N-4O-u1_N-Sp-2NOS-1C",
    group = 
"""
1 *2 C u0     r0 {2,D} {3,S}
2 *3 N u[1,2] r0 {1,D}
3 *4 H u0     {1,S}
4 *1 O u2     r0
""",
    kinetics = None,
)

entry(
    index = 103,
    label = "Root_1R!H->C_N-2R!H->C_N-4R->H_N-4CNO->O",
    group = 
"""
1 *2 C     u0         {2,[S,D,B]} {3,S}
2 *3 N     u[1,2]     {1,[S,D,B]}
3 *4 H     u0         {1,S}
4 *1 [N,C] u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 104,
    label = "Root_1R!H->C_N-2R!H->C_N-4R->H_N-4CNO->O_Sp-2NOS-1C",
    group = 
"""
1 *2 C     u0 {2,S} {3,S}
2 *3 N     u1 {1,S}
3 *4 H     u0 r0 {1,S}
4 *1 [N,C] u1
""",
    kinetics = None,
)

entry(
    index = 105,
    label = "Root_1R!H->C_N-2R!H->C_N-4R->H_N-4CNO->O_N-Sp-2NOS-1C",
    group = 
"""
1 *2 C     u0         {2,D} {3,S}
2 *3 N     u[1,2]     {1,D}
3 *4 H     u0         {1,S}
4 *1 [N,C] u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 106,
    label = "Root_1R!H->C_N-2R!H->C_N-4R->H_N-4CNO->O_N-Sp-2NOS-1C_Ext-2NOS-R",
    group = 
"""
1 *2 C     u0 {2,D} {3,S}
2 *3 N     u1 {1,D} {5,S}
3 *4 H     u0 {1,S}
4 *1 [N,C] u1
5    O     u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 107,
    label = "Root_1R!H->C_N-2R!H->C_N-4R->H_N-4CNO->O_N-Sp-2NOS-1C_Ext-2NOS-R_4CN->N",
    group = 
"""
1 *2 C u0 {2,D} {3,S}
2 *3 N u1 {1,D} {5,S}
3 *4 H u0 r0 {1,S}
4 *1 N u1
5    O u0 r0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 108,
    label = "Root_1R!H->C_N-2R!H->C_N-4R->H_N-4CNO->O_N-Sp-2NOS-1C_Ext-2NOS-R_N-4CN->N",
    group = 
"""
1 *2 C u0 {2,D} {3,S}
2 *3 N u1 {1,D} {5,S}
3 *4 H u0 r0 {1,S}
4 *1 C u1
5    O u0 r0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 109,
    label = "Root_1R!H->C_N-2R!H->C_N-4R->H_N-4CNO->O_N-Sp-2NOS-1C_4CN->N",
    group = 
"""
1 *2 C u0         {2,D} {3,S}
2 *3 N u[1,2]     {1,D}
3 *4 H u0         {1,S}
4 *1 N u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 110,
    label = "Root_1R!H->C_N-2R!H->C_N-4R->H_N-4CNO->O_N-Sp-2NOS-1C_N-4CN->N",
    group = 
"""
1 *2 C u0         {2,D} {3,S}
2 *3 N u[1,2]     {1,D}
3 *4 H u0         {1,S}
4 *1 C u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 111,
    label = "Root_N-1R!H->C",
    group = 
"""
1 *2 [I,P,Br,Cl,O,Si,S,N,F] u0         {2,[S,D,B]} {3,S}
2 *3 R!H                    u[1,2]     {1,[S,D,B]}
3 *4 H                      u0         {1,S}
4 *1 R                      u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 112,
    label = "Root_N-1R!H->C_4R->H",
    group = 
"""
1 *2 [I,P,Br,Cl,O,Si,S,N,F] u0         {2,[S,D,B]} {3,S}
2 *3 R!H                    u[1,2]     {1,[S,D,B]}
3 *4 H                      u0         {1,S}
4 *1 H                      u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 113,
    label = "Root_N-1R!H->C_4R->H_2R!H->O",
    group = 
"""
1 *2 [I,P,Br,Cl,O,Si,S,N,F] u0     {2,[S,D,B]} {3,S}
2 *3 O                      u[1,2] {1,[S,D,B]}
3 *4 H                      u0     r0 {1,S}
4 *1 H                      u1    
""",
    kinetics = None,
)

entry(
    index = 114,
    label = "Root_N-1R!H->C_4R->H_N-2R!H->O",
    group = 
"""
1 *2 [I,P,Br,Cl,O,Si,S,N,F] u0         {2,[S,D,B]} {3,S}
2 *3 [N,C]                  u[1,2]     {1,[S,D,B]}
3 *4 H                      u0         {1,S}
4 *1 H                      u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 115,
    label = "Root_N-1R!H->C_4R->H_N-2R!H->O_2CN-u1",
    group = 
"""
1 *2 [I,P,Br,Cl,O,Si,S,N,F] u0         {2,[S,D,B]} {3,S}
2 *3 [N,C]                  u1         {1,[S,D,B]}
3 *4 H                      u0         {1,S}
4 *1 H                      u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 116,
    label = "Root_N-1R!H->C_4R->H_N-2R!H->O_2CN-u1_2CN->N",
    group = 
"""
1 *2 [I,P,Br,Cl,O,Si,S,N,F] u0         {2,[S,D,B]} {3,S}
2 *3 N                      u1         {1,[S,D,B]}
3 *4 H                      u0         {1,S}
4 *1 H                      u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 117,
    label = "Root_N-1R!H->C_4R->H_N-2R!H->O_2CN-u1_2CN->N_1BrClFINOPSSi->N",
    group = 
"""
1 *2 N u0 {2,[S,D,B]} {3,S}
2 *3 N u1 {1,[S,D,B]}
3 *4 H u0 {1,S}
4 *1 H u1
""",
    kinetics = None,
)

entry(
    index = 118,
    label = "Root_N-1R!H->C_4R->H_N-2R!H->O_2CN-u1_2CN->N_1BrClFINOPSSi->N_Sp-2N-1N",
    group = 
"""
1 *2 N u0 {2,S} {3,S}
2 *3 N u1 {1,S}
3 *4 H u0 r0 {1,S}
4 *1 H u1
""",
    kinetics = None,
)

entry(
    index = 119,
    label = "Root_N-1R!H->C_4R->H_N-2R!H->O_2CN-u1_2CN->N_1BrClFINOPSSi->N_N-Sp-2N-1N",
    group = 
"""
1 *2 N u0 {2,D} {3,S}
2 *3 N u1 {1,D}
3 *4 H u0 r0 {1,S}
4 *1 H u1
""",
    kinetics = None,
)

entry(
    index = 120,
    label = "Root_N-1R!H->C_4R->H_N-2R!H->O_2CN-u1_2CN->N_N-1BrClFINOPSSi->N",
    group = 
"""
1 *2 O u0         r0 {2,[S,D,B]} {3,S}
2 *3 N u1         r0 {1,[S,D,B]}
3 *4 H u0         {1,S}
4 *1 H u[1,2,3,4] r0
""",
    kinetics = None,
)

entry(
    index = 121,
    label = "Root_N-1R!H->C_4R->H_N-2R!H->O_2CN-u1_N-2CN->N",
    group = 
"""
1 *2 [I,P,Br,Cl,O,Si,S,N,F] u0         {2,[S,D,B]} {3,S}
2 *3 C                      u1         {1,[S,D,B]}
3 *4 H                      u0         {1,S}
4 *1 H                      u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 122,
    label = "Root_N-1R!H->C_4R->H_N-2R!H->O_2CN-u1_N-2CN->N_Sp-2C-1BrClFINOPSSi",
    group = 
"""
1 *2 [I,P,Br,Cl,O,Si,S,N,F] u0 {2,S} {3,S}
2 *3 C                      u1 {1,S}
3 *4 H                      u0 {1,S}
4 *1 H                      u1
""",
    kinetics = None,
)

entry(
    index = 123,
    label = "Root_N-1R!H->C_4R->H_N-2R!H->O_2CN-u1_N-2CN->N_Sp-2C-1BrClFINOPSSi_1BrClFINOPSSi->N",
    group = 
"""
1 *2 N u0 {2,S} {3,S}
2 *3 C u1 {1,S}
3 *4 H u0 r0 {1,S}
4 *1 H u1
""",
    kinetics = None,
)

entry(
    index = 124,
    label = "Root_N-1R!H->C_4R->H_N-2R!H->O_2CN-u1_N-2CN->N_Sp-2C-1BrClFINOPSSi_N-1BrClFINOPSSi->N",
    group = 
"""
1 *2 O u0 {2,S} {3,S}
2 *3 C u1 {1,S}
3 *4 H u0 r0 {1,S}
4 *1 H u1
""",
    kinetics = None,
)

entry(
    index = 125,
    label = "Root_N-1R!H->C_4R->H_N-2R!H->O_2CN-u1_N-2CN->N_N-Sp-2C-1BrClFINOPSSi",
    group = 
"""
1 *2 [I,P,Br,Cl,O,Si,S,N,F] u0         r0 {2,D} {3,S}
2 *3 C                      u1         r0 {1,D}
3 *4 H                      u0         {1,S}
4 *1 H                      u[1,2,3,4] r0
""",
    kinetics = None,
)

entry(
    index = 126,
    label = "Root_N-1R!H->C_4R->H_N-2R!H->O_N-2CN-u1",
    group = 
"""
1 *2 [I,P,Br,Cl,O,Si,S,N,F] u0         r0 {2,[S,D,B]} {3,S}
2 *3 [N,C]                  u2         r0 {1,[S,D,B]}
3 *4 H                      u0         {1,S}
4 *1 H                      u[1,2,3,4] r0
""",
    kinetics = None,
)

entry(
    index = 127,
    label = "Root_N-1R!H->C_N-4R->H",
    group = 
"""
1 *2 [I,P,Br,Cl,O,Si,S,N,F] u0         {2,[S,D,B]} {3,S}
2 *3 R!H                    u[1,2]     {1,[S,D,B]}
3 *4 H                      u0         {1,S}
4 *1 [S,N,C,O]              u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 128,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O",
    group = 
"""
1 *2 [I,P,Br,Cl,O,Si,S,N,F] u0         {2,[S,D,B]} {3,S}
2 *3 R!H                    u[1,2]     {1,[S,D,B]}
3 *4 H                      u0         {1,S}
4 *1 O                      u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 129,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi",
    group = 
"""
1 *2 [I,P,Br,Cl,O,Si,S,N,F] u0         {2,S} {3,S}
2 *3 R!H                    u[1,2]     {1,S}
3 *4 H                      u0         {1,S}
4 *1 O                      u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 130,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_2R!H->C",
    group = 
"""
1 *2 [I,P,Br,Cl,O,Si,S,N,F] u0         {2,S} {3,S}
2 *3 C                      u[1,2]     {1,S}
3 *4 H                      u0         {1,S}
4 *1 O                      u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 131,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_2R!H->C_4O-u1",
    group = 
"""
1 *2 [I,P,Br,Cl,O,Si,S,N,F] u0     {2,S} {3,S}
2 *3 C                      u[1,2] {1,S}
3 *4 H                      u0     {1,S}
4 *1 O                      u1    
""",
    kinetics = None,
)

entry(
    index = 132,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_2R!H->C_4O-u1_1BrClFINOPSSi->N",
    group = 
"""
1 *2 N u0     {2,S} {3,S}
2 *3 C u[1,2] {1,S}
3 *4 H u0     r0 {1,S}
4 *1 O u1    
""",
    kinetics = None,
)

entry(
    index = 133,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_2R!H->C_4O-u1_N-1BrClFINOPSSi->N",
    group = 
"""
1 *2 O u0     {2,S} {3,S}
2 *3 C u[1,2] {1,S}
3 *4 H u0     {1,S}
4 *1 O u1    
""",
    kinetics = None,
)

entry(
    index = 134,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_2R!H->C_4O-u1_N-1BrClFINOPSSi->N_Ext-4O-R",
    group = 
"""
1 *2 O   u0     {2,S} {3,S}
2 *3 C   u[1,2] {1,S}
3 *4 H   u0     {1,S}
4 *1 O   u1     {5,[S,D,T,B,Q]}
5    R!H ux     {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 135,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_2R!H->C_4O-u1_N-1BrClFINOPSSi->N_Ext-4O-R_5R!H-u0",
    group = 
"""
1 *2 O   u0 {2,S} {3,S}
2 *3 C   u1 {1,S}
3 *4 H   u0 {1,S}
4 *1 O   u1 {5,[S,D,T,B,Q]}
5    R!H u0 {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 136,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_2R!H->C_4O-u1_N-1BrClFINOPSSi->N_Ext-4O-R_5R!H-u0_5R!H->C",
    group = 
"""
1 *2 O u0 r0 {2,S} {3,S}
2 *3 C u1 r0 {1,S}
3 *4 H u0 {1,S}
4 *1 O u1 r0 {5,[S,D,T,B,Q]}
5    C u0 {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 137,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_2R!H->C_4O-u1_N-1BrClFINOPSSi->N_Ext-4O-R_5R!H-u0_N-5R!H->C",
    group = 
"""
1 *2 O u0 r0 {2,S} {3,S}
2 *3 C u1 r0 {1,S}
3 *4 H u0 {1,S}
4 *1 O u1 r0 {5,[S,D,T,B,Q]}
5    O u0 {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 138,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_2R!H->C_4O-u1_N-1BrClFINOPSSi->N_Ext-4O-R_N-5R!H-u0",
    group = 
"""
1 *2 O   u0       {2,S} {3,S}
2 *3 C   u[1,2]   {1,S}
3 *4 H   u0       r0 {1,S}
4 *1 O   u1       {5,S}
5    R!H u[1,2,3] r0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 139,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_2R!H->C_N-4O-u1",
    group = 
"""
1 *2 [I,P,Br,Cl,O,Si,S,N,F] u0     {2,S} {3,S}
2 *3 C                      u[1,2] {1,S}
3 *4 H                      u0     {1,S}
4 *1 O                      u2    
""",
    kinetics = None,
)

entry(
    index = 140,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_2R!H->C_N-4O-u1_1BrClFINOPSSi->N",
    group = 
"""
1 *2 N u0     {2,S} {3,S}
2 *3 C u[1,2] {1,S}
3 *4 H u0     r0 {1,S}
4 *1 O u2    
""",
    kinetics = None,
)

entry(
    index = 141,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_2R!H->C_N-4O-u1_N-1BrClFINOPSSi->N",
    group = 
"""
1 *2 O u0     {2,S} {3,S}
2 *3 C u[1,2] {1,S}
3 *4 H u0     r0 {1,S}
4 *1 O u2    
""",
    kinetics = None,
)

entry(
    index = 142,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C",
    group = 
"""
1 *2 [I,P,Br,Cl,O,Si,S,N,F] u0         {2,S} {3,S}
2 *3 [N,O]                  u[1,2]     {1,S}
3 *4 H                      u0         {1,S}
4 *1 O                      u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 143,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_Ext-4O-R",
    group = 
"""
1 *2 [I,P,Br,Cl,O,Si,S,N,F] u0         {2,S} {3,S}
2 *3 [N,O]                  u[1,2]     {1,S}
3 *4 H                      u0         {1,S}
4 *1 O                      u[1,2,3,4] {5,[S,D,T,B,Q]}
5    R!H                    ux         {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 144,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_Ext-4O-R_1BrClFINOPSSi->N",
    group = 
"""
1 *2 N     u0         {2,S} {3,S}
2 *3 [N,O] u[1,2]     {1,S}
3 *4 H     u0         {1,S}
4 *1 O     u[1,2,3,4] {5,[S,D,T,B,Q]}
5    O     ux         {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 145,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_Ext-4O-R_1BrClFINOPSSi->N_2NO->N",
    group = 
"""
1 *2 N u0     {2,S} {3,S}
2 *3 N u[1,2] {1,S}
3 *4 H u0     {1,S}
4 *1 O u1     {5,S}
5    O u0     {4,S}
""",
    kinetics = None,
)

entry(
    index = 146,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_Ext-4O-R_1BrClFINOPSSi->N_2NO->N_2N-u1",
    group = 
"""
1 *2 N u0 {2,S} {3,S}
2 *3 N u1 {1,S}
3 *4 H u0 r0 {1,S}
4 *1 O u1 {5,S}
5    O u0 r0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 147,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_Ext-4O-R_1BrClFINOPSSi->N_2NO->N_N-2N-u1",
    group = 
"""
1 *2 N u0 {2,S} {3,S}
2 *3 N u2 {1,S}
3 *4 H u0 r0 {1,S}
4 *1 O u1 {5,S}
5    O u0 r0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 148,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_Ext-4O-R_1BrClFINOPSSi->N_N-2NO->N",
    group = 
"""
1 *2 N u0         r0 {2,S} {3,S}
2 *3 O u[1,2]     r0 {1,S}
3 *4 H u0         {1,S}
4 *1 O u[1,2,3,4] r0 {5,[S,D,T,B,Q]}
5    O ux         {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 149,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_Ext-4O-R_N-1BrClFINOPSSi->N",
    group = 
"""
1 *2 O     u0         {2,S} {3,S}
2 *3 [N,O] u1         {1,S}
3 *4 H     u0         {1,S}
4 *1 O     u[1,2,3,4] {5,[S,D,T,B,Q]}
5    R!H   ux         {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 150,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_Ext-4O-R_N-1BrClFINOPSSi->N_2NO->N",
    group = 
"""
1 *2 O   u0         r0 {2,S} {3,S}
2 *3 N   u1         r0 {1,S}
3 *4 H   u0         {1,S}
4 *1 O   u[1,2,3,4] r0 {5,[S,D,T,B,Q]}
5    R!H ux         {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 151,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_Ext-4O-R_N-1BrClFINOPSSi->N_N-2NO->N",
    group = 
"""
1 *2 O   u0         r0 {2,S} {3,S}
2 *3 O   u1         r0 {1,S}
3 *4 H   u0         {1,S}
4 *1 O   u[1,2,3,4] r0 {5,[S,D,T,B,Q]}
5    R!H ux         {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 152,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_4O-u1",
    group = 
"""
1 *2 [I,P,Br,Cl,O,Si,S,N,F] u0     {2,S} {3,S}
2 *3 [N,O]                  u[1,2] {1,S}
3 *4 H                      u0     {1,S}
4 *1 O                      u1    
""",
    kinetics = None,
)

entry(
    index = 153,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_4O-u1_1BrClFINOPSSi->N",
    group = 
"""
1 *2 N     u0     {2,S} {3,S}
2 *3 [N,O] u[1,2] {1,S}
3 *4 H     u0     {1,S}
4 *1 O     u1    
""",
    kinetics = None,
)

entry(
    index = 154,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_4O-u1_1BrClFINOPSSi->N_2NO->N",
    group = 
"""
1 *2 N u0     {2,S} {3,S}
2 *3 N u[1,2] {1,S}
3 *4 H u0     {1,S}
4 *1 O u1    
""",
    kinetics = None,
)

entry(
    index = 155,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_4O-u1_1BrClFINOPSSi->N_2NO->N_2N-u1",
    group = 
"""
1 *2 N u0 r0 {2,S} {3,S}
2 *3 N u1 r0 {1,S}
3 *4 H u0 r0 {1,S}
4 *1 O u1 r0
""",
    kinetics = None,
)

entry(
    index = 156,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_4O-u1_1BrClFINOPSSi->N_2NO->N_N-2N-u1",
    group = 
"""
1 *2 N u0 r0 {2,S} {3,S}
2 *3 N u2 r0 {1,S}
3 *4 H u0 r0 {1,S}
4 *1 O u1 r0
""",
    kinetics = None,
)

entry(
    index = 157,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_4O-u1_1BrClFINOPSSi->N_N-2NO->N",
    group = 
"""
1 *2 N u0     {2,S} {3,S}
2 *3 O u[1,2] {1,S}
3 *4 H u0     {1,S}
4 *1 O u1    
""",
    kinetics = None,
)

entry(
    index = 158,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_4O-u1_N-1BrClFINOPSSi->N",
    group = 
"""
1 *2 O     u0     r0 {2,S} {3,S}
2 *3 [N,O] u[1,2] r0 {1,S}
3 *4 H     u0     r0 {1,S}
4 *1 O     u1     r0
""",
    kinetics = None,
)

entry(
    index = 159,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_N-4O-u1",
    group = 
"""
1 *2 [I,P,Br,Cl,O,Si,S,N,F] u0     {2,S} {3,S}
2 *3 [N,O]                  u[1,2] {1,S}
3 *4 H                      u0     {1,S}
4 *1 O                      u2    
""",
    kinetics = None,
)

entry(
    index = 160,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_N-4O-u1_2NO-u1",
    group = 
"""
1 *2 [I,P,Br,Cl,O,Si,S,N,F] u0 {2,S} {3,S}
2 *3 [N,O]                  u1 {1,S}
3 *4 H                      u0 {1,S}
4 *1 O                      u2
""",
    kinetics = None,
)

entry(
    index = 161,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_N-4O-u1_2NO-u1_1BrClFINOPSSi->N",
    group = 
"""
1 *2 N     u0 {2,S} {3,S}
2 *3 [N,O] u1 {1,S}
3 *4 H     u0 {1,S}
4 *1 O     u2
""",
    kinetics = None,
)

entry(
    index = 162,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_N-4O-u1_2NO-u1_1BrClFINOPSSi->N_2NO->N",
    group = 
"""
1 *2 N u0 r0 {2,S} {3,S}
2 *3 N u1 r0 {1,S}
3 *4 H u0 r0 {1,S}
4 *1 O u2 r0
""",
    kinetics = None,
)

entry(
    index = 163,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_N-4O-u1_2NO-u1_1BrClFINOPSSi->N_N-2NO->N",
    group = 
"""
1 *2 N u0 r0 {2,S} {3,S}
2 *3 O u1 r0 {1,S}
3 *4 H u0 r0 {1,S}
4 *1 O u2 r0
""",
    kinetics = None,
)

entry(
    index = 164,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_N-4O-u1_2NO-u1_N-1BrClFINOPSSi->N",
    group = 
"""
1 *2 O     u0 {2,S} {3,S}
2 *3 [N,O] u1 {1,S}
3 *4 H     u0 {1,S}
4 *1 O     u2
""",
    kinetics = None,
)

entry(
    index = 165,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_N-4O-u1_N-2NO-u1",
    group = 
"""
1 *2 [I,P,Br,Cl,O,Si,S,N,F] u0 r0 {2,S} {3,S}
2 *3 [N,O]                  u2 r0 {1,S}
3 *4 H                      u0 r0 {1,S}
4 *1 O                      u2 r0
""",
    kinetics = None,
)

entry(
    index = 166,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_N-Sp-2R!H-1BrClFINOPSSi",
    group = 
"""
1 *2 N   u0         {2,D} {3,S}
2 *3 R!H u[1,2]     {1,D}
3 *4 H   u0         {1,S}
4 *1 O   u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 167,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_N-Sp-2R!H-1BrClFINOPSSi_4O-u1",
    group = 
"""
1 *2 N   u0     {2,D} {3,S}
2 *3 R!H u[1,2] {1,D}
3 *4 H   u0     {1,S}
4 *1 O   u1    
""",
    kinetics = None,
)

entry(
    index = 168,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_N-Sp-2R!H-1BrClFINOPSSi_4O-u1_Ext-4O-R",
    group = 
"""
1 *2 N u0 {2,D} {3,S}
2 *3 N u1 {1,D}
3 *4 H u0 {1,S}
4 *1 O u1 {5,S}
5    O ux {4,S}
""",
    kinetics = None,
)

entry(
    index = 169,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_N-Sp-2R!H-1BrClFINOPSSi_4O-u1_Ext-4O-R_5R!H-u0",
    group = 
"""
1 *2 N u0 {2,D} {3,S}
2 *3 N u1 {1,D}
3 *4 H u0 r0 {1,S}
4 *1 O u1 {5,S}
5    O u0 r0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 170,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_N-Sp-2R!H-1BrClFINOPSSi_4O-u1_Ext-4O-R_N-5R!H-u0",
    group = 
"""
1 *2 N u0       {2,D} {3,S}
2 *3 N u1       {1,D}
3 *4 H u0       r0 {1,S}
4 *1 O u1       {5,S}
5    O u[1,2,3] r0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 171,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_N-Sp-2R!H-1BrClFINOPSSi_4O-u1_2R!H->N",
    group = 
"""
1 *2 N u0     {2,D} {3,S}
2 *3 N u[1,2] {1,D}
3 *4 H u0     {1,S}
4 *1 O u1    
""",
    kinetics = None,
)

entry(
    index = 172,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_N-Sp-2R!H-1BrClFINOPSSi_4O-u1_N-2R!H->N",
    group = 
"""
1 *2 N u0     {2,D} {3,S}
2 *3 C u[1,2] {1,D}
3 *4 H u0     {1,S}
4 *1 O u1    
""",
    kinetics = None,
)

entry(
    index = 173,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_N-Sp-2R!H-1BrClFINOPSSi_N-4O-u1",
    group = 
"""
1 *2 N   u0     {2,D} {3,S}
2 *3 R!H u[1,2] {1,D}
3 *4 H   u0     {1,S}
4 *1 O   u2    
""",
    kinetics = None,
)

entry(
    index = 174,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_N-Sp-2R!H-1BrClFINOPSSi_N-4O-u1_2R!H->N",
    group = 
"""
1 *2 N u0     r0 {2,D} {3,S}
2 *3 N u[1,2] r0 {1,D}
3 *4 H u0     {1,S}
4 *1 O u2     r0
""",
    kinetics = None,
)

entry(
    index = 175,
    label = "Root_N-1R!H->C_N-4R->H_4CNOS->O_N-Sp-2R!H-1BrClFINOPSSi_N-4O-u1_N-2R!H->N",
    group = 
"""
1 *2 N u0     r0 {2,D} {3,S}
2 *3 C u[1,2] r0 {1,D}
3 *4 H u0     {1,S}
4 *1 O u2     r0
""",
    kinetics = None,
)

entry(
    index = 176,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O",
    group = 
"""
1 *2 [I,P,Br,Cl,O,Si,S,N,F] u0         {2,[S,D,B]} {3,S}
2 *3 R!H                    u[1,2]     {1,[S,D,B]}
3 *4 H                      u0         {1,S}
4 *1 [N,C,S]                u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 177,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_2R!H->C",
    group = 
"""
1 *2 [I,P,Br,Cl,O,Si,S,N,F] u0         {2,[S,D,B]} {3,S}
2 *3 C                      u[1,2]     {1,[S,D,B]}
3 *4 H                      u0         {1,S}
4 *1 [N,C,S]                u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 178,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_2R!H->C_1BrClFINOPSSi->O",
    group = 
"""
1 *2 O u0         {2,[S,D,B]} {3,S}
2 *3 C u[1,2]     {1,[S,D,B]}
3 *4 H u0         {1,S}
4 *1 C u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 179,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_2R!H->C_1BrClFINOPSSi->O_4CNS-u1",
    group = 
"""
1 *2 O u0     {2,[S,D,B]} {3,S}
2 *3 C u[1,2] {1,[S,D,B]}
3 *4 H u0     {1,S}
4 *1 C u1    
""",
    kinetics = None,
)

entry(
    index = 180,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_2R!H->C_1BrClFINOPSSi->O_4CNS-u1_Ext-4CNS-R",
    group = 
"""
1 *2 O   u0     {2,[S,D,B]} {3,S}
2 *3 C   u[1,2] {1,[S,D,B]}
3 *4 H   u0     {1,S}
4 *1 C   u1     {5,[S,D,T,B,Q]}
5    R!H ux     {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 181,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_2R!H->C_1BrClFINOPSSi->O_4CNS-u1_Ext-4CNS-R_Sp-5R!H=4CCNNSS",
    group = 
"""
1 *2 O   u0 {2,[S,D,B]} {3,S}
2 *3 C   u1 {1,[S,D,B]}
3 *4 H   u0 {1,S}
4 *1 C   u1 {5,D}
5    R!H ux {4,D}
""",
    kinetics = None,
)

entry(
    index = 182,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_2R!H->C_1BrClFINOPSSi->O_4CNS-u1_Ext-4CNS-R_Sp-5R!H=4CCNNSS_5R!H->C",
    group = 
"""
1 *2 O u0 {2,[S,D,B]} {3,S}
2 *3 C u1 {1,[S,D,B]}
3 *4 H u0 r0 {1,S}
4 *1 C u1 {5,D}
5    C ux {4,D}
""",
    kinetics = None,
)

entry(
    index = 183,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_2R!H->C_1BrClFINOPSSi->O_4CNS-u1_Ext-4CNS-R_Sp-5R!H=4CCNNSS_N-5R!H->C",
    group = 
"""
1 *2 O u0 {2,[S,D,B]} {3,S}
2 *3 C u1 {1,[S,D,B]}
3 *4 H u0 r0 {1,S}
4 *1 C u1 {5,D}
5    O ux {4,D}
""",
    kinetics = None,
)

entry(
    index = 184,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_2R!H->C_1BrClFINOPSSi->O_4CNS-u1_Ext-4CNS-R_N-Sp-5R!H=4CCNNSS",
    group = 
"""
1 *2 O   u0     {2,[S,D,B]} {3,S}
2 *3 C   u[1,2] {1,[S,D,B]}
3 *4 H   u0     {1,S}
4 *1 C   u1     {5,[S,T,Q,B]}
5    R!H ux     {4,[S,T,Q,B]}
""",
    kinetics = None,
)

entry(
    index = 185,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_2R!H->C_1BrClFINOPSSi->O_4CNS-u1_Ext-4CNS-R_N-Sp-5R!H=4CCNNSS_Ext-4CNS-R",
    group = 
"""
1 *2 O   u0     {2,S} {3,S}
2 *3 C   u[1,2] {1,S}
3 *4 H   u0     {1,S}
4 *1 C   u1     {5,S} {6,[S,D,T,B,Q]}
5    C   u0     {4,S}
6    R!H ux     {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 186,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_2R!H->C_1BrClFINOPSSi->O_4CNS-u1_Ext-4CNS-R_N-Sp-5R!H=4CCNNSS_Ext-4CNS-R_Ext-4CNS-R",
    group = 
"""
1 *2 O   u0     r0 {2,S} {3,S}
2 *3 C   u[1,2] r0 {1,S}
3 *4 H   u0     {1,S}
4 *1 C   u1     r0 {5,S} {6,[S,D,T,B,Q]} {7,[S,D,T,B,Q]}
5    C   u0     r0 {4,S}
6    R!H ux     {4,[S,D,T,B,Q]}
7    R!H ux     {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 187,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_2R!H->C_1BrClFINOPSSi->O_4CNS-u1_Ext-4CNS-R_N-Sp-5R!H=4CCNNSS_Ext-5R!H-R",
    group = 
"""
1 *2 O   u0     {2,[S,D,B]} {3,S}
2 *3 C   u[1,2] {1,[S,D,B]}
3 *4 H   u0     {1,S}
4 *1 C   u1     {5,[S,T,Q,B]}
5    R!H ux     {4,[S,T,Q,B]} {6,[S,D,T,B,Q]}
6    R!H ux     {5,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 188,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_2R!H->C_1BrClFINOPSSi->O_4CNS-u1_Ext-4CNS-R_N-Sp-5R!H=4CCNNSS_Sp-5R!H-4CNS",
    group = 
"""
1 *2 O   u0 {2,S} {3,S}
2 *3 C   u1 {1,S}
3 *4 H   u0 {1,S}
4 *1 C   u1 {5,S}
5    R!H u0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 189,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_2R!H->C_1BrClFINOPSSi->O_4CNS-u1_Ext-4CNS-R_N-Sp-5R!H=4CCNNSS_Sp-5R!H-4CNS_5R!H->C",
    group = 
"""
1 *2 O u0 r0 {2,S} {3,S}
2 *3 C u1 r0 {1,S}
3 *4 H u0 r0 {1,S}
4 *1 C u1 r0 {5,S}
5    C u0 r0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 190,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_2R!H->C_1BrClFINOPSSi->O_4CNS-u1_Ext-4CNS-R_N-Sp-5R!H=4CCNNSS_Sp-5R!H-4CNS_N-5R!H->C",
    group = 
"""
1 *2 O u0 r0 {2,S} {3,S}
2 *3 C u1 r0 {1,S}
3 *4 H u0 r0 {1,S}
4 *1 C u1 r0 {5,S}
5    O u0 r0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 191,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_2R!H->C_1BrClFINOPSSi->O_4CNS-u1_Ext-4CNS-R_N-Sp-5R!H=4CCNNSS_N-Sp-5R!H-4CNS",
    group = 
"""
1 *2 O   u0     {2,[S,D,B]} {3,S}
2 *3 C   u[1,2] {1,[S,D,B]}
3 *4 H   u0     {1,S}
4 *1 C   u1     {5,T}
5    R!H ux     {4,T}
""",
    kinetics = None,
)

entry(
    index = 192,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_2R!H->C_1BrClFINOPSSi->O_N-4CNS-u1",
    group = 
"""
1 *2 O u0     r0 {2,S} {3,S}
2 *3 C u[1,2] r0 {1,S}
3 *4 H u0     {1,S}
4 *1 C u2     r0
""",
    kinetics = None,
)

entry(
    index = 193,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_2R!H->C_N-1BrClFINOPSSi->O",
    group = 
"""
1 *2 [N,S]   u0         {2,[S,D,B]} {3,S}
2 *3 C       u[1,2]     {1,[S,D,B]}
3 *4 H       u0         {1,S}
4 *1 [N,C,S] u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 194,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_2R!H->C_N-1BrClFINOPSSi->O_1NS->N",
    group = 
"""
1 *2 N u0         {2,[S,D,B]} {3,S}
2 *3 C u1         {1,[S,D,B]}
3 *4 H u0         {1,S}
4 *1 C u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 195,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_2R!H->C_N-1BrClFINOPSSi->O_1NS->N_Sp-2C-1N",
    group = 
"""
1 *2 N u0         {2,S} {3,S}
2 *3 C u1         {1,S}
3 *4 H u0         r0 {1,S}
4 *1 C u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 196,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_2R!H->C_N-1BrClFINOPSSi->O_1NS->N_N-Sp-2C-1N",
    group = 
"""
1 *2 N u0         {2,D} {3,S}
2 *3 C u1         {1,D}
3 *4 H u0         r0 {1,S}
4 *1 C u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 197,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_2R!H->C_N-1BrClFINOPSSi->O_N-1NS->N",
    group = 
"""
1 *2 S       u0     r0 {2,[S,D,B]} {3,S}
2 *3 C       u[1,2] r0 {1,[S,D,B]}
3 *4 H       u0     {1,S}
4 *1 [N,C,S] u1     r0
""",
    kinetics = None,
)

entry(
    index = 198,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C",
    group = 
"""
1 *2 [I,P,Br,Cl,O,Si,S,N,F] u0         {2,[S,D,B]} {3,S}
2 *3 [N,O]                  u[1,2]     {1,[S,D,B]}
3 *4 H                      u0         {1,S}
4 *1 [N,C,S]                u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 199,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_4CNS->N",
    group = 
"""
1 *2 [I,P,Br,Cl,O,Si,S,N,F] u0         {2,[S,D,B]} {3,S}
2 *3 [N,O]                  u[1,2]     {1,[S,D,B]}
3 *4 H                      u0         {1,S}
4 *1 N                      u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 200,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_4CNS->N_Ext-4N-R",
    group = 
"""
1 *2 [I,P,Br,Cl,O,Si,S,N,F] u0         {2,[S,D,B]} {3,S}
2 *3 [N,O]                  u[1,2]     {1,[S,D,B]}
3 *4 H                      u0         {1,S}
4 *1 N                      u[1,2,3,4] {5,[S,D,T,B,Q]}
5    R!H                    ux         {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 201,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_4CNS->N_Ext-4N-R_5R!H->N",
    group = 
"""
1 *2 [I,P,Br,Cl,O,Si,S,N,F] u0 {2,[S,D,B]} {3,S}
2 *3 [N,O]                  u1 {1,[S,D,B]}
3 *4 H                      u0 r0 {1,S}
4 *1 N                      u1 {5,[S,D,T,B,Q]}
5    N                      u0 r0 {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 202,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_4CNS->N_Ext-4N-R_N-5R!H->N",
    group = 
"""
1 *2 [I,P,Br,Cl,O,Si,S,N,F] u0         {2,[S,D,B]} {3,S}
2 *3 [N,O]                  u[1,2]     {1,[S,D,B]}
3 *4 H                      u0         {1,S}
4 *1 N                      u[1,2,3,4] {5,[S,D,T,B,Q]}
5    [I,P,Br,Cl,C,O,Si,S,F] ux         {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 203,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_4CNS->N_Ext-4N-R_N-5R!H->N_Sp-5BrCClFIOPSSi-4N",
    group = 
"""
1 *2 [I,P,Br,Cl,O,Si,S,N,F] u0         r0 {2,[S,D,B]} {3,S}
2 *3 [N,O]                  u[1,2]     r0 {1,[S,D,B]}
3 *4 H                      u0         {1,S}
4 *1 N                      u[1,2,3,4] r0 {5,S}
5    [I,P,Br,Cl,C,O,Si,S,F] ux         {4,S}
""",
    kinetics = None,
)

entry(
    index = 204,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_4CNS->N_Ext-4N-R_N-5R!H->N_N-Sp-5BrCClFIOPSSi-4N",
    group = 
"""
1 *2 [I,P,Br,Cl,O,Si,S,N,F] u0 {2,[S,D,B]} {3,S}
2 *3 [N,O]                  u1 {1,[S,D,B]}
3 *4 H                      u0 {1,S}
4 *1 N                      u1 {5,D}
5    [I,P,Br,Cl,C,O,Si,S,F] u0 {4,D}
""",
    kinetics = None,
)

entry(
    index = 205,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_4CNS->N_Ext-4N-R_N-5R!H->N_N-Sp-5BrCClFIOPSSi-4N_1BrClFINOPSSi->N",
    group = 
"""
1 *2 N                      u0 {2,[S,D,B]} {3,S}
2 *3 [N,O]                  u1 {1,[S,D,B]}
3 *4 H                      u0 r0 {1,S}
4 *1 N                      u1 {5,D}
5    [I,P,Br,Cl,C,O,Si,S,F] u0 r0 {4,D}
""",
    kinetics = None,
)

entry(
    index = 206,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_4CNS->N_Ext-4N-R_N-5R!H->N_N-Sp-5BrCClFIOPSSi-4N_N-1BrClFINOPSSi->N",
    group = 
"""
1 *2 O                      u0 {2,[S,D,B]} {3,S}
2 *3 [N,O]                  u1 {1,[S,D,B]}
3 *4 H                      u0 r0 {1,S}
4 *1 N                      u1 {5,D}
5    [I,P,Br,Cl,C,O,Si,S,F] u0 r0 {4,D}
""",
    kinetics = None,
)

entry(
    index = 207,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_4CNS->N_2NO-u1",
    group = 
"""
1 *2 [I,P,Br,Cl,O,Si,S,N,F] u0 {2,[S,D,B]} {3,S}
2 *3 [N,O]                  u1 {1,[S,D,B]}
3 *4 H                      u0 {1,S}
4 *1 N                      u1
""",
    kinetics = None,
)

entry(
    index = 208,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_4CNS->N_2NO-u1_Sp-2NO-1BrClFINNOOPSSi",
    group = 
"""
1 *2 [I,P,Br,Cl,O,Si,S,N,F] u0 {2,S} {3,S}
2 *3 [N,O]                  u1 {1,S}
3 *4 H                      u0 {1,S}
4 *1 N                      u1
""",
    kinetics = None,
)

entry(
    index = 209,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_4CNS->N_2NO-u1_Sp-2NO-1BrClFINNOOPSSi_1BrClFINOPSSi->N",
    group = 
"""
1 *2 N     u0 {2,S} {3,S}
2 *3 [N,O] u1 {1,S}
3 *4 H     u0 {1,S}
4 *1 N     u1
""",
    kinetics = None,
)

entry(
    index = 210,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_4CNS->N_2NO-u1_Sp-2NO-1BrClFINNOOPSSi_1BrClFINOPSSi->N_2NO->N",
    group = 
"""
1 *2 N u0 r0 {2,S} {3,S}
2 *3 N u1 r0 {1,S}
3 *4 H u0 r0 {1,S}
4 *1 N u1 r0
""",
    kinetics = None,
)

entry(
    index = 211,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_4CNS->N_2NO-u1_Sp-2NO-1BrClFINNOOPSSi_1BrClFINOPSSi->N_N-2NO->N",
    group = 
"""
1 *2 N u0 r0 {2,S} {3,S}
2 *3 O u1 r0 {1,S}
3 *4 H u0 r0 {1,S}
4 *1 N u1 r0
""",
    kinetics = None,
)

entry(
    index = 212,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_4CNS->N_2NO-u1_Sp-2NO-1BrClFINNOOPSSi_N-1BrClFINOPSSi->N",
    group = 
"""
1 *2 O     u0 {2,S} {3,S}
2 *3 [N,O] u1 {1,S}
3 *4 H     u0 {1,S}
4 *1 N     u1
""",
    kinetics = None,
)

entry(
    index = 213,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_4CNS->N_2NO-u1_Sp-2NO-1BrClFINNOOPSSi_N-1BrClFINOPSSi->N_2NO->N",
    group = 
"""
1 *2 O u0 r0 {2,S} {3,S}
2 *3 N u1 r0 {1,S}
3 *4 H u0 r0 {1,S}
4 *1 N u1 r0
""",
    kinetics = None,
)

entry(
    index = 214,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_4CNS->N_2NO-u1_Sp-2NO-1BrClFINNOOPSSi_N-1BrClFINOPSSi->N_N-2NO->N",
    group = 
"""
1 *2 O u0 r0 {2,S} {3,S}
2 *3 O u1 r0 {1,S}
3 *4 H u0 r0 {1,S}
4 *1 N u1 r0
""",
    kinetics = None,
)

entry(
    index = 215,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_4CNS->N_2NO-u1_N-Sp-2NO-1BrClFINNOOPSSi",
    group = 
"""
1 *2 [I,P,Br,Cl,O,Si,S,N,F] u0 r0 {2,D} {3,S}
2 *3 [N,O]                  u1 r0 {1,D}
3 *4 H                      u0 r0 {1,S}
4 *1 N                      u1 r0
""",
    kinetics = None,
)

entry(
    index = 216,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_4CNS->N_N-2NO-u1",
    group = 
"""
1 *2 [I,P,Br,Cl,O,Si,S,N,F] u0         {2,[S,D,B]} {3,S}
2 *3 [N,O]                  u2         {1,[S,D,B]}
3 *4 H                      u0         {1,S}
4 *1 N                      u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 217,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_N-4CNS->N",
    group = 
"""
1 *2 [I,P,Br,Cl,O,Si,S,N,F] u0         {2,[S,D,B]} {3,S}
2 *3 [N,O]                  u[1,2]     {1,[S,D,B]}
3 *4 H                      u0         {1,S}
4 *1 C                      u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 218,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_N-4CNS->N_2NO-u1",
    group = 
"""
1 *2 [I,P,Br,Cl,O,Si,S,N,F] u0         {2,[S,D,B]} {3,S}
2 *3 [N,O]                  u1         {1,[S,D,B]}
3 *4 H                      u0         {1,S}
4 *1 C                      u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 219,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_N-4CNS->N_2NO-u1_1BrClFINOPSSi->N",
    group = 
"""
1 *2 N     u0         {2,S} {3,S}
2 *3 [N,O] u1         {1,S}
3 *4 H     u0         {1,S}
4 *1 C     u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 220,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_N-4CNS->N_2NO-u1_1BrClFINOPSSi->N_2NO->N",
    group = 
"""
1 *2 N u0         r0 {2,S} {3,S}
2 *3 N u1         r0 {1,S}
3 *4 H u0         {1,S}
4 *1 C u[1,2,3,4] r0
""",
    kinetics = None,
)

entry(
    index = 221,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_N-4CNS->N_2NO-u1_1BrClFINOPSSi->N_N-2NO->N",
    group = 
"""
1 *2 N u0         r0 {2,S} {3,S}
2 *3 O u1         r0 {1,S}
3 *4 H u0         {1,S}
4 *1 C u[1,2,3,4] r0
""",
    kinetics = None,
)

entry(
    index = 222,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_N-4CNS->N_2NO-u1_N-1BrClFINOPSSi->N",
    group = 
"""
1 *2 O     u0 {2,[S,D,B]} {3,S}
2 *3 [N,O] u1 {1,[S,D,B]}
3 *4 H     u0 r0 {1,S}
4 *1 C     u1
""",
    kinetics = None,
)

entry(
    index = 223,
    label = "Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_N-4CNS->N_N-2NO-u1",
    group = 
"""
1 *2 [I,P,Br,Cl,O,Si,S,N,F] u0         r0 {2,S} {3,S}
2 *3 [N,O]                  u2         r0 {1,S}
3 *4 H                      u0         {1,S}
4 *1 C                      u[1,2,3,4] r0
""",
    kinetics = None,
)

tree(
"""
L1: Root
    L2: Root_1R!H->C
        L3: Root_1R!H->C_Ext-4R-R
            L4: Root_1R!H->C_Ext-4R-R_Sp-5R!H#4R
                L5: Root_1R!H->C_Ext-4R-R_Sp-5R!H#4R_Ext-1C-R
                    L6: Root_1R!H->C_Ext-4R-R_Sp-5R!H#4R_Ext-1C-R_Ext-1C-R
            L4: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R
                L5: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_5R!H->S
                    L6: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_5R!H->S_Ext-2R!H-R
                L5: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S
                    L6: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0
                        L7: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R
                            L8: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_Sp-6R!H=1C
                                L9: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_Sp-6R!H=1C_Sp-5CO-4R
                                    L10: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_Sp-6R!H=1C_Sp-5CO-4R_Ext-5CO-R
                                    L10: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_Sp-6R!H=1C_Sp-5CO-4R_Ext-4R-R
                                        L11: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_Sp-6R!H=1C_Sp-5CO-4R_Ext-4R-R_Ext-4R-R
                                L9: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_Sp-6R!H=1C_N-Sp-5CO-4R
                            L8: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C
                                L9: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_Ext-1C-R
                                    L10: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_Ext-1C-R_5CO->O
                                    L10: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_Ext-1C-R_N-5CO->O
                                        L11: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_Ext-1C-R_N-5CO->O_Ext-4R-R
                                            L12: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_Ext-1C-R_N-5CO->O_Ext-4R-R_Ext-4R-R
                                        L11: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_Ext-1C-R_N-5CO->O_Sp-5C-4R
                                            L12: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_Ext-1C-R_N-5CO->O_Sp-5C-4R_Ext-5C-R
                                                L13: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_Ext-1C-R_N-5CO->O_Sp-5C-4R_Ext-5C-R_4R->C
                                                L13: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_Ext-1C-R_N-5CO->O_Sp-5C-4R_Ext-5C-R_N-4R->C
                                            L12: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_Ext-1C-R_N-5CO->O_Sp-5C-4R_4R->C
                                            L12: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_Ext-1C-R_N-5CO->O_Sp-5C-4R_N-4R->C
                                        L11: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_Ext-1C-R_N-5CO->O_N-Sp-5C-4R
                                L9: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_4R->C
                                    L10: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_4R->C_Sp-5CCOO=4C
                                    L10: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_4R->C_N-Sp-5CCOO=4C
                                        L11: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_4R->C_N-Sp-5CCOO=4C_2R!H->C
                                            L12: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_4R->C_N-Sp-5CCOO=4C_2R!H->C_5CO->O
                                            L12: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_4R->C_N-Sp-5CCOO=4C_2R!H->C_N-5CO->O
                                                L13: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_4R->C_N-Sp-5CCOO=4C_2R!H->C_N-5CO->O_Ext-4C-R
                                                    L14: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_4R->C_N-Sp-5CCOO=4C_2R!H->C_N-5CO->O_Ext-4C-R_1C-inRing
                                                    L14: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_4R->C_N-Sp-5CCOO=4C_2R!H->C_N-5CO->O_Ext-4C-R_N-1C-inRing
                                                        L15: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_4R->C_N-Sp-5CCOO=4C_2R!H->C_N-5CO->O_Ext-4C-R_N-1C-inRing_Ext-4C-R
                                                L13: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_4R->C_N-Sp-5CCOO=4C_2R!H->C_N-5CO->O_Ext-5C-R
                                        L11: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_4R->C_N-Sp-5CCOO=4C_N-2R!H->C
                                            L12: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_4R->C_N-Sp-5CCOO=4C_N-2R!H->C_Ext-5CO-R_Ext-4C-R_Ext-7R!H-R_Ext-5CO-R
                                L9: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-1C-R_N-Sp-6R!H=1C_N-4R->C
                        L7: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-4R-R
                            L8: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-4R-R_Ext-2R!H-R
                            L8: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_Ext-4R-R_Ext-4R-R
                        L7: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_2R!H->S
                        L7: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_N-2R!H->S
                            L8: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_N-2R!H->S_Sp-5CO-4R
                                L9: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_N-2R!H->S_Sp-5CO-4R_5CO->O
                                    L10: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_N-2R!H->S_Sp-5CO-4R_5CO->O_2CN->N
                                    L10: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_N-2R!H->S_Sp-5CO-4R_5CO->O_N-2CN->N
                                L9: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_N-2R!H->S_Sp-5CO-4R_N-5CO->O
                                    L10: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_N-2R!H->S_Sp-5CO-4R_N-5CO->O_Ext-5C-R
                            L8: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_5CO-u0_N-2R!H->S_N-Sp-5CO-4R
                    L6: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_N-5CO-u0
                        L7: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_N-5CO-u0_Ext-2R!H-R
                        L7: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_N-5CO-u0_Ext-1C-R
                            L8: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_N-5CO-u0_Ext-1C-R_Sp-6R!H-1C
                                L9: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_N-5CO-u0_Ext-1C-R_Sp-6R!H-1C_Ext-1C-R
                                    L10: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_N-5CO-u0_Ext-1C-R_Sp-6R!H-1C_Ext-1C-R_Ext-6R!H-R
                                        L11: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_N-5CO-u0_Ext-1C-R_Sp-6R!H-1C_Ext-1C-R_Ext-6R!H-R_Ext-7R!H-R
                                L9: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_N-5CO-u0_Ext-1C-R_Sp-6R!H-1C_Ext-6R!H-R
                            L8: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_N-5CO-u0_Ext-1C-R_N-Sp-6R!H-1C
                        L7: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_N-5CO-u0_Sp-2R!H-1C
                        L7: Root_1R!H->C_Ext-4R-R_N-Sp-5R!H#4R_N-5R!H->S_N-5CO-u0_N-Sp-2R!H-1C
        L3: Root_1R!H->C_2R!H->C
            L4: Root_1R!H->C_2R!H->C_4R->O
                L5: Root_1R!H->C_2R!H->C_4R->O_Ext-1C-R
                    L6: Root_1R!H->C_2R!H->C_4R->O_Ext-1C-R_Sp-5R!H-1C
                        L7: Root_1R!H->C_2R!H->C_4R->O_Ext-1C-R_Sp-5R!H-1C_Ext-1C-R
                    L6: Root_1R!H->C_2R!H->C_4R->O_Ext-1C-R_N-Sp-5R!H-1C
            L4: Root_1R!H->C_2R!H->C_N-4R->O
                L5: Root_1R!H->C_2R!H->C_N-4R->O_4CHN->H
                    L6: Root_1R!H->C_2R!H->C_N-4R->O_4CHN->H_Ext-1C-R
                        L7: Root_1R!H->C_2R!H->C_N-4R->O_4CHN->H_Ext-1C-R_Ext-1C-R
                L5: Root_1R!H->C_2R!H->C_N-4R->O_N-4CHN->H
                    L6: Root_1R!H->C_2R!H->C_N-4R->O_N-4CHN->H_Ext-1C-R
                        L7: Root_1R!H->C_2R!H->C_N-4R->O_N-4CHN->H_Ext-1C-R_Ext-1C-R
                        L7: Root_1R!H->C_2R!H->C_N-4R->O_N-4CHN->H_Ext-1C-R_Sp-5R!H-1C
                            L8: Root_1R!H->C_2R!H->C_N-4R->O_N-4CHN->H_Ext-1C-R_Sp-5R!H-1C_4C-u1
                            L8: Root_1R!H->C_2R!H->C_N-4R->O_N-4CHN->H_Ext-1C-R_Sp-5R!H-1C_N-4C-u1
                        L7: Root_1R!H->C_2R!H->C_N-4R->O_N-4CHN->H_Ext-1C-R_N-Sp-5R!H-1C
                    L6: Root_1R!H->C_2R!H->C_N-4R->O_N-4CHN->H_4C-u1
                    L6: Root_1R!H->C_2R!H->C_N-4R->O_N-4CHN->H_N-4C-u1
        L3: Root_1R!H->C_N-2R!H->C
            L4: Root_1R!H->C_N-2R!H->C_4R->H
                L5: Root_1R!H->C_N-2R!H->C_4R->H_Ext-2NOS-R
                L5: Root_1R!H->C_N-2R!H->C_4R->H_Sp-2NOS-1C
                    L6: Root_1R!H->C_N-2R!H->C_4R->H_Sp-2NOS-1C_2NOS->N
                    L6: Root_1R!H->C_N-2R!H->C_4R->H_Sp-2NOS-1C_N-2NOS->N
                L5: Root_1R!H->C_N-2R!H->C_4R->H_N-Sp-2NOS-1C
            L4: Root_1R!H->C_N-2R!H->C_N-4R->H
                L5: Root_1R!H->C_N-2R!H->C_N-4R->H_4CNO->O
                    L6: Root_1R!H->C_N-2R!H->C_N-4R->H_4CNO->O_4O-u1
                        L7: Root_1R!H->C_N-2R!H->C_N-4R->H_4CNO->O_4O-u1_Sp-2NOS-1C
                        L7: Root_1R!H->C_N-2R!H->C_N-4R->H_4CNO->O_4O-u1_N-Sp-2NOS-1C
                            L8: Root_1R!H->C_N-2R!H->C_N-4R->H_4CNO->O_4O-u1_N-Sp-2NOS-1C_Ext-2NOS-R
                    L6: Root_1R!H->C_N-2R!H->C_N-4R->H_4CNO->O_N-4O-u1
                        L7: Root_1R!H->C_N-2R!H->C_N-4R->H_4CNO->O_N-4O-u1_Sp-2NOS-1C
                        L7: Root_1R!H->C_N-2R!H->C_N-4R->H_4CNO->O_N-4O-u1_N-Sp-2NOS-1C
                L5: Root_1R!H->C_N-2R!H->C_N-4R->H_N-4CNO->O
                    L6: Root_1R!H->C_N-2R!H->C_N-4R->H_N-4CNO->O_Sp-2NOS-1C
                    L6: Root_1R!H->C_N-2R!H->C_N-4R->H_N-4CNO->O_N-Sp-2NOS-1C
                        L7: Root_1R!H->C_N-2R!H->C_N-4R->H_N-4CNO->O_N-Sp-2NOS-1C_Ext-2NOS-R
                            L8: Root_1R!H->C_N-2R!H->C_N-4R->H_N-4CNO->O_N-Sp-2NOS-1C_Ext-2NOS-R_4CN->N
                            L8: Root_1R!H->C_N-2R!H->C_N-4R->H_N-4CNO->O_N-Sp-2NOS-1C_Ext-2NOS-R_N-4CN->N
                        L7: Root_1R!H->C_N-2R!H->C_N-4R->H_N-4CNO->O_N-Sp-2NOS-1C_4CN->N
                        L7: Root_1R!H->C_N-2R!H->C_N-4R->H_N-4CNO->O_N-Sp-2NOS-1C_N-4CN->N
    L2: Root_N-1R!H->C
        L3: Root_N-1R!H->C_4R->H
            L4: Root_N-1R!H->C_4R->H_2R!H->O
            L4: Root_N-1R!H->C_4R->H_N-2R!H->O
                L5: Root_N-1R!H->C_4R->H_N-2R!H->O_2CN-u1
                    L6: Root_N-1R!H->C_4R->H_N-2R!H->O_2CN-u1_2CN->N
                        L7: Root_N-1R!H->C_4R->H_N-2R!H->O_2CN-u1_2CN->N_1BrClFINOPSSi->N
                            L8: Root_N-1R!H->C_4R->H_N-2R!H->O_2CN-u1_2CN->N_1BrClFINOPSSi->N_Sp-2N-1N
                            L8: Root_N-1R!H->C_4R->H_N-2R!H->O_2CN-u1_2CN->N_1BrClFINOPSSi->N_N-Sp-2N-1N
                        L7: Root_N-1R!H->C_4R->H_N-2R!H->O_2CN-u1_2CN->N_N-1BrClFINOPSSi->N
                    L6: Root_N-1R!H->C_4R->H_N-2R!H->O_2CN-u1_N-2CN->N
                        L7: Root_N-1R!H->C_4R->H_N-2R!H->O_2CN-u1_N-2CN->N_Sp-2C-1BrClFINOPSSi
                            L8: Root_N-1R!H->C_4R->H_N-2R!H->O_2CN-u1_N-2CN->N_Sp-2C-1BrClFINOPSSi_1BrClFINOPSSi->N
                            L8: Root_N-1R!H->C_4R->H_N-2R!H->O_2CN-u1_N-2CN->N_Sp-2C-1BrClFINOPSSi_N-1BrClFINOPSSi->N
                        L7: Root_N-1R!H->C_4R->H_N-2R!H->O_2CN-u1_N-2CN->N_N-Sp-2C-1BrClFINOPSSi
                L5: Root_N-1R!H->C_4R->H_N-2R!H->O_N-2CN-u1
        L3: Root_N-1R!H->C_N-4R->H
            L4: Root_N-1R!H->C_N-4R->H_4CNOS->O
                L5: Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi
                    L6: Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_2R!H->C
                        L7: Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_2R!H->C_4O-u1
                            L8: Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_2R!H->C_4O-u1_1BrClFINOPSSi->N
                            L8: Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_2R!H->C_4O-u1_N-1BrClFINOPSSi->N
                                L9: Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_2R!H->C_4O-u1_N-1BrClFINOPSSi->N_Ext-4O-R
                                    L10: Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_2R!H->C_4O-u1_N-1BrClFINOPSSi->N_Ext-4O-R_5R!H-u0
                                        L11: Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_2R!H->C_4O-u1_N-1BrClFINOPSSi->N_Ext-4O-R_5R!H-u0_5R!H->C
                                        L11: Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_2R!H->C_4O-u1_N-1BrClFINOPSSi->N_Ext-4O-R_5R!H-u0_N-5R!H->C
                                    L10: Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_2R!H->C_4O-u1_N-1BrClFINOPSSi->N_Ext-4O-R_N-5R!H-u0
                        L7: Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_2R!H->C_N-4O-u1
                            L8: Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_2R!H->C_N-4O-u1_1BrClFINOPSSi->N
                            L8: Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_2R!H->C_N-4O-u1_N-1BrClFINOPSSi->N
                    L6: Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C
                        L7: Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_Ext-4O-R
                            L8: Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_Ext-4O-R_1BrClFINOPSSi->N
                                L9: Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_Ext-4O-R_1BrClFINOPSSi->N_2NO->N
                                    L10: Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_Ext-4O-R_1BrClFINOPSSi->N_2NO->N_2N-u1
                                    L10: Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_Ext-4O-R_1BrClFINOPSSi->N_2NO->N_N-2N-u1
                                L9: Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_Ext-4O-R_1BrClFINOPSSi->N_N-2NO->N
                            L8: Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_Ext-4O-R_N-1BrClFINOPSSi->N
                                L9: Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_Ext-4O-R_N-1BrClFINOPSSi->N_2NO->N
                                L9: Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_Ext-4O-R_N-1BrClFINOPSSi->N_N-2NO->N
                        L7: Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_4O-u1
                            L8: Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_4O-u1_1BrClFINOPSSi->N
                                L9: Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_4O-u1_1BrClFINOPSSi->N_2NO->N
                                    L10: Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_4O-u1_1BrClFINOPSSi->N_2NO->N_2N-u1
                                    L10: Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_4O-u1_1BrClFINOPSSi->N_2NO->N_N-2N-u1
                                L9: Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_4O-u1_1BrClFINOPSSi->N_N-2NO->N
                            L8: Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_4O-u1_N-1BrClFINOPSSi->N
                        L7: Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_N-4O-u1
                            L8: Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_N-4O-u1_2NO-u1
                                L9: Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_N-4O-u1_2NO-u1_1BrClFINOPSSi->N
                                    L10: Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_N-4O-u1_2NO-u1_1BrClFINOPSSi->N_2NO->N
                                    L10: Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_N-4O-u1_2NO-u1_1BrClFINOPSSi->N_N-2NO->N
                                L9: Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_N-4O-u1_2NO-u1_N-1BrClFINOPSSi->N
                            L8: Root_N-1R!H->C_N-4R->H_4CNOS->O_Sp-2R!H-1BrClFINOPSSi_N-2R!H->C_N-4O-u1_N-2NO-u1
                L5: Root_N-1R!H->C_N-4R->H_4CNOS->O_N-Sp-2R!H-1BrClFINOPSSi
                    L6: Root_N-1R!H->C_N-4R->H_4CNOS->O_N-Sp-2R!H-1BrClFINOPSSi_4O-u1
                        L7: Root_N-1R!H->C_N-4R->H_4CNOS->O_N-Sp-2R!H-1BrClFINOPSSi_4O-u1_Ext-4O-R
                            L8: Root_N-1R!H->C_N-4R->H_4CNOS->O_N-Sp-2R!H-1BrClFINOPSSi_4O-u1_Ext-4O-R_5R!H-u0
                            L8: Root_N-1R!H->C_N-4R->H_4CNOS->O_N-Sp-2R!H-1BrClFINOPSSi_4O-u1_Ext-4O-R_N-5R!H-u0
                        L7: Root_N-1R!H->C_N-4R->H_4CNOS->O_N-Sp-2R!H-1BrClFINOPSSi_4O-u1_2R!H->N
                        L7: Root_N-1R!H->C_N-4R->H_4CNOS->O_N-Sp-2R!H-1BrClFINOPSSi_4O-u1_N-2R!H->N
                    L6: Root_N-1R!H->C_N-4R->H_4CNOS->O_N-Sp-2R!H-1BrClFINOPSSi_N-4O-u1
                        L7: Root_N-1R!H->C_N-4R->H_4CNOS->O_N-Sp-2R!H-1BrClFINOPSSi_N-4O-u1_2R!H->N
                        L7: Root_N-1R!H->C_N-4R->H_4CNOS->O_N-Sp-2R!H-1BrClFINOPSSi_N-4O-u1_N-2R!H->N
            L4: Root_N-1R!H->C_N-4R->H_N-4CNOS->O
                L5: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_2R!H->C
                    L6: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_2R!H->C_1BrClFINOPSSi->O
                        L7: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_2R!H->C_1BrClFINOPSSi->O_4CNS-u1
                            L8: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_2R!H->C_1BrClFINOPSSi->O_4CNS-u1_Ext-4CNS-R
                                L9: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_2R!H->C_1BrClFINOPSSi->O_4CNS-u1_Ext-4CNS-R_Sp-5R!H=4CCNNSS
                                    L10: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_2R!H->C_1BrClFINOPSSi->O_4CNS-u1_Ext-4CNS-R_Sp-5R!H=4CCNNSS_5R!H->C
                                    L10: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_2R!H->C_1BrClFINOPSSi->O_4CNS-u1_Ext-4CNS-R_Sp-5R!H=4CCNNSS_N-5R!H->C
                                L9: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_2R!H->C_1BrClFINOPSSi->O_4CNS-u1_Ext-4CNS-R_N-Sp-5R!H=4CCNNSS
                                    L10: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_2R!H->C_1BrClFINOPSSi->O_4CNS-u1_Ext-4CNS-R_N-Sp-5R!H=4CCNNSS_Ext-4CNS-R
                                        L11: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_2R!H->C_1BrClFINOPSSi->O_4CNS-u1_Ext-4CNS-R_N-Sp-5R!H=4CCNNSS_Ext-4CNS-R_Ext-4CNS-R
                                    L10: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_2R!H->C_1BrClFINOPSSi->O_4CNS-u1_Ext-4CNS-R_N-Sp-5R!H=4CCNNSS_Ext-5R!H-R
                                    L10: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_2R!H->C_1BrClFINOPSSi->O_4CNS-u1_Ext-4CNS-R_N-Sp-5R!H=4CCNNSS_Sp-5R!H-4CNS
                                        L11: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_2R!H->C_1BrClFINOPSSi->O_4CNS-u1_Ext-4CNS-R_N-Sp-5R!H=4CCNNSS_Sp-5R!H-4CNS_5R!H->C
                                        L11: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_2R!H->C_1BrClFINOPSSi->O_4CNS-u1_Ext-4CNS-R_N-Sp-5R!H=4CCNNSS_Sp-5R!H-4CNS_N-5R!H->C
                                    L10: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_2R!H->C_1BrClFINOPSSi->O_4CNS-u1_Ext-4CNS-R_N-Sp-5R!H=4CCNNSS_N-Sp-5R!H-4CNS
                        L7: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_2R!H->C_1BrClFINOPSSi->O_N-4CNS-u1
                    L6: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_2R!H->C_N-1BrClFINOPSSi->O
                        L7: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_2R!H->C_N-1BrClFINOPSSi->O_1NS->N
                            L8: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_2R!H->C_N-1BrClFINOPSSi->O_1NS->N_Sp-2C-1N
                            L8: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_2R!H->C_N-1BrClFINOPSSi->O_1NS->N_N-Sp-2C-1N
                        L7: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_2R!H->C_N-1BrClFINOPSSi->O_N-1NS->N
                L5: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C
                    L6: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_4CNS->N
                        L7: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_4CNS->N_Ext-4N-R
                            L8: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_4CNS->N_Ext-4N-R_5R!H->N
                            L8: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_4CNS->N_Ext-4N-R_N-5R!H->N
                                L9: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_4CNS->N_Ext-4N-R_N-5R!H->N_Sp-5BrCClFIOPSSi-4N
                                L9: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_4CNS->N_Ext-4N-R_N-5R!H->N_N-Sp-5BrCClFIOPSSi-4N
                                    L10: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_4CNS->N_Ext-4N-R_N-5R!H->N_N-Sp-5BrCClFIOPSSi-4N_1BrClFINOPSSi->N
                                    L10: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_4CNS->N_Ext-4N-R_N-5R!H->N_N-Sp-5BrCClFIOPSSi-4N_N-1BrClFINOPSSi->N
                        L7: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_4CNS->N_2NO-u1
                            L8: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_4CNS->N_2NO-u1_Sp-2NO-1BrClFINNOOPSSi
                                L9: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_4CNS->N_2NO-u1_Sp-2NO-1BrClFINNOOPSSi_1BrClFINOPSSi->N
                                    L10: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_4CNS->N_2NO-u1_Sp-2NO-1BrClFINNOOPSSi_1BrClFINOPSSi->N_2NO->N
                                    L10: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_4CNS->N_2NO-u1_Sp-2NO-1BrClFINNOOPSSi_1BrClFINOPSSi->N_N-2NO->N
                                L9: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_4CNS->N_2NO-u1_Sp-2NO-1BrClFINNOOPSSi_N-1BrClFINOPSSi->N
                                    L10: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_4CNS->N_2NO-u1_Sp-2NO-1BrClFINNOOPSSi_N-1BrClFINOPSSi->N_2NO->N
                                    L10: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_4CNS->N_2NO-u1_Sp-2NO-1BrClFINNOOPSSi_N-1BrClFINOPSSi->N_N-2NO->N
                            L8: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_4CNS->N_2NO-u1_N-Sp-2NO-1BrClFINNOOPSSi
                        L7: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_4CNS->N_N-2NO-u1
                    L6: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_N-4CNS->N
                        L7: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_N-4CNS->N_2NO-u1
                            L8: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_N-4CNS->N_2NO-u1_1BrClFINOPSSi->N
                                L9: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_N-4CNS->N_2NO-u1_1BrClFINOPSSi->N_2NO->N
                                L9: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_N-4CNS->N_2NO-u1_1BrClFINOPSSi->N_N-2NO->N
                            L8: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_N-4CNS->N_2NO-u1_N-1BrClFINOPSSi->N
                        L7: Root_N-1R!H->C_N-4R->H_N-4CNOS->O_N-2R!H->C_N-4CNS->N_N-2NO-u1
"""
)

forbidden(
    label = "O2d",
    group = 
"""
1 *2 O u0 {2,D}
2 *3 O u0 {1,D}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

forbidden(
    label = "OS_XH_birad_singlet",
    group = 
"""
1 *3 [O,S] u0 p3 {2,[S,D,T]}
2 *2 R!H   ux {1,[S,D,T]} {3,S}
3 *4 H     u0 {2,S}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

forbidden(
    label = "O_Srad",
    group = 
"""
1 *2 [O,S] u0 p2 {2,S} {3,S}
2 *3 [O,S] u1 p2 {1,S}
3 *4 H     u0 {1,S}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

forbidden(
    label = "XH_N_birad_singlet",
    group = 
"""
1 *3 N   u0 p2 {2,[S,D]}
2 *2 R!H ux {1,[S,D]} {3,S}
3 *4 H   u0 {2,S}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

forbidden(
    label = "XH_birad_singlet",
    group = 
"""
1 *3 [C,Si] u0 p1 {2,[S,D,T]}
2 *2 R!H    ux {1,[S,D,T]} {3,S}
3 *4 H      u0 {2,S}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

forbidden(
    label = "XH_quadrad_singlet",
    group = 
"""
1 *3 [C,Si] u0 p2 {2,[S,D,T]}
2 *2 R!H    ux {1,[S,D,T]} {3,S}
3 *4 H      u0 {2,S}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

