#!/usr/bin/env python
# encoding: utf-8

name = "O2 dissociative adsorption"
shortDesc = ""
longDesc = """
"""

autoGenerated=False
entry(
    index = 0,
    label = "O2 + X + X <=> OX + OX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.07, n=0, Ea=(0, 'kJ/mol'), T0=(1,'K')),
)
entry(
    index = 1,
    label = "CO + X <=> OCX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.84, n=0, Ea=(0, 'kJ/mol'), T0=(1,'K')),
)


