#!/usr/bin/env python
# encoding: utf-8

name = "O2_lib"
shortDesc = ""
longDesc = """

"""
autoGenerated=False
entry(
    index = 0,
    label = "O2 + X + X <=> OX + OX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.0601503, n=0.00140166, Ea=(0,'kJ/mol'), T0=(1,'K'),
        comment = """Generated for Fe from a BEP rule fit to several O2 dissociative adsorption rules across multiple metals
    Fitting script lives here: https://github.com/sevyharris/nitridation/blob/main/O2_kinetics/fit_O2_sticking_BEP.py
    """,
    )
)

