#!/usr/bin/env python
# encoding: utf-8

name = "Peroxyl_Disproportionation/groups"
shortDesc = ""
longDesc = """

"""

template(reactants=["Root"], products=["RO_rad", "RO_rad", "O2"], ownReverse=False)

reverse = "Peroxyl_Disproportionation_reverse"
reversible = True

reactantNum = 2

productNum = 3

autoGenerated = True

recipe(actions=[
    ['BREAK_BOND', '*1', 1, '*2'],
    ['BREAK_BOND', '*3', 1, '*4'],
    ['FORM_BOND', '*2', 1, '*4'],
    ['GAIN_RADICAL', '*1', '1'],
    ['GAIN_RADICAL', '*3', '1'],
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1 *1 O u0 {3,S} {4,S}
2 *3 O u0 {5,S} {6,S}
3    R u0 {1,S}
4 *2 O u1 {1,S}
5    R u0 {2,S}
6 *4 O u1 {2,S}
""",
    kinetics = None,
)

entry(
    index = 1,
    label = "Root_Ext-5R-R",
    group = 
"""
1 *3 O   u0 {2,S} {4,S}
2    C   u0 {1,S} {5,[S,D,T,B,Q]}
3 *1 O   u0 {6,S} {7,S}
4 *4 O   u1 {1,S}
5    R!H ux {2,[S,D,T,B,Q]}
6    C   u0 {3,S}
7 *2 O   u1 {3,S}
""",
    kinetics = None,
)

entry(
    index = 2,
    label = "Root_Ext-5R-R_7R!H->C",
    group = 
"""
1 *3 O u0 {2,S} {4,S}
2    C u0 {1,S} {5,[S,D,T,B,Q]}
3 *1 O u0 {6,S} {7,S}
4 *4 O u1 {1,S}
5    C ux {2,[S,D,T,B,Q]}
6    C u0 {3,S}
7 *2 O u1 {3,S}
""",
    kinetics = None,
)

entry(
    index = 3,
    label = "Root_Ext-5R-R_7R!H->C_7C-inRing",
    group = 
"""
1 *3 O u0 {2,S} {4,S}
2    C u0 {1,S} {5,[S,D,T,B,Q]}
3 *1 O u0 {6,S} {7,S}
4 *4 O u1 {1,S}
5    C ux r1 {2,[S,D,T,B,Q]}
6    C u0 {3,S}
7 *2 O u1 {3,S}
""",
    kinetics = None,
)

entry(
    index = 4,
    label = "Root_Ext-5R-R_7R!H->C_7C-inRing_Ext-7C-R_Ext-8R!H-R_Ext-8R!H-R",
    group = 
"""
1    C   u0 r0 {2,S} {3,S} {5,[S,D,T,B,Q]}
2 *3 O   u0 r0 {1,S} {6,S}
3    C   u0 r0 {1,S} {7,[S,D,T,B,Q]}
4 *1 O   u0 r0 {8,S} {9,S}
5    C   ux r1 {1,[S,D,T,B,Q]}
6 *4 O   u1 r0 {2,S}
7    R!H ux {3,[S,D,T,B,Q]}
8    C   u0 r0 {4,S}
9 *2 O   u1 r0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 5,
    label = "Root_Ext-5R-R_7R!H->C_N-7C-inRing",
    group = 
"""
1 *3 O u0 {2,S} {4,S}
2    C u0 {1,S} {5,S}
3 *1 O u0 {6,S} {7,S}
4 *4 O u1 {1,S}
5    C u0 r0 {2,S}
6    C u0 {3,S}
7 *2 O u1 {3,S}
""",
    kinetics = None,
)

entry(
    index = 6,
    label = "Root_Ext-5R-R_7R!H->C_N-7C-inRing_Ext-5R-R",
    group = 
"""
1    C   u0 {2,S} {4,S} {5,[S,D,T,B,Q]}
2 *3 O   u0 {1,S} {6,S}
3 *1 O   u0 {7,S} {8,S}
4    C   u0 r0 {1,S}
5    R!H ux {1,[S,D,T,B,Q]}
6 *4 O   u1 {2,S}
7    C   u0 {3,S}
8 *2 O   u1 {3,S}
""",
    kinetics = None,
)

entry(
    index = 7,
    label = "Root_Ext-5R-R_N-7R!H->C",
    group = 
"""
1 *3 O                      u0 {2,S} {4,S}
2    C                      u0 {1,S} {5,S}
3 *1 O                      u0 {6,S} {7,S}
4 *4 O                      u1 {1,S}
5    [Br,Cl,O,F,S,N,P,Si,I] u0 {2,S}
6    C                      u0 {3,S}
7 *2 O                      u1 {3,S}
""",
    kinetics = None,
)

entry(
    index = 8,
    label = "Root_Ext-3R-R",
    group = 
"""
1 *1 O     u0 {2,S} {4,S}
2    C     u0 {1,S} {5,[S,D]}
3 *3 O     u0 {6,S} {7,S}
4 *2 O     u1 {1,S}
5    [O,C] u0 {2,[S,D]}
6    R     u0 {3,S}
7 *4 O     u1 {3,S}
""",
    kinetics = None,
)

entry(
    index = 9,
    label = "Root_Ext-3R-R_5R->C",
    group = 
"""
1 *1 O     u0 r0 {2,S} {4,S}
2    C     u0 r0 {1,S} {5,[S,D]}
3 *3 O     u0 r0 {6,S} {7,S}
4 *2 O     u1 r0 {1,S}
5    [O,C] u0 r0 {2,[S,D]}
6    C     u0 r0 {3,S}
7 *4 O     u1 r0 {3,S}
""",
    kinetics = None,
)

entry(
    index = 10,
    label = "Root_Ext-3R-R_N-5R->C",
    group = 
"""
1 *1 O     u0 r0 {2,S} {4,S}
2    C     u0 r0 {1,S} {5,[S,D]}
3 *3 O     u0 r0 {6,S} {7,S}
4 *2 O     u1 r0 {1,S}
5    [O,C] u0 r0 {2,[S,D]}
6    H     u0 r0 {3,S}
7 *4 O     u1 r0 {3,S}
""",
    kinetics = None,
)

tree(
"""
L1: Root
    L2: Root_Ext-5R-R
        L3: Root_Ext-5R-R_7R!H->C
            L4: Root_Ext-5R-R_7R!H->C_7C-inRing
                L5: Root_Ext-5R-R_7R!H->C_7C-inRing_Ext-7C-R_Ext-8R!H-R_Ext-8R!H-R
            L4: Root_Ext-5R-R_7R!H->C_N-7C-inRing
                L5: Root_Ext-5R-R_7R!H->C_N-7C-inRing_Ext-5R-R
        L3: Root_Ext-5R-R_N-7R!H->C
    L2: Root_Ext-3R-R
        L3: Root_Ext-3R-R_5R->C
        L3: Root_Ext-3R-R_N-5R->C
"""
)

