# Script to compute covariance matrices for each of the BM tree nodes

import os
import copy
import re
import time
import pickle
import numpy as np
import pandas as pd
import shutil
import glob
import subprocess
import concurrent.futures
import warnings
from scipy.optimize import OptimizeWarning
warnings.filterwarnings("ignore", category=OptimizeWarning)

import rmgpy.data.thermo
import rmgpy.data.rmg
import rmgpy.chemkin

import rmgpy.tools.uncertainty

import matplotlib.pyplot as plt


start_time = time.time()

# 1. load the database
# load the tree from the database
database = rmgpy.data.rmg.RMGDatabase()
database.load(
    path = rmgpy.settings['database.directory'],
    thermo_libraries = [
        'Klippenstein_Glarborg2016',
        'BurkeH2O2',
        'thermo_DFT_CCSDTF12_BAC', 
        'DFT_QCI_thermo',
        'primaryThermoLibrary',
        'primaryNS',
        'NitrogenCurran',
        'NOx2018',
        'FFCM1(-)',
        'SulfurLibrary',
        'SulfurGlarborgH2S',
        'SABIC_aromatics'
    ],
    transport_libraries = [],
    reaction_libraries = [],
    seed_mechanisms = [],
    kinetics_families = 'default',
    kinetics_depositories = ['training'],
    depository = False,
) 

for family in database.kinetics.families:
    if not database.kinetics.families[family].auto_generated:
        database.kinetics.families[family].add_rules_from_training(thermo_database=database.thermo)
        database.kinetics.families[family].fill_rules_by_averaging_up(verbose=True)

# 2. get the mapping of training reactions to tree nodes
autogenerated_families = []
reaction_maps = {}
training_maps = {}  # contains the order of training reaction memory addresses
for family_name in database.kinetics.families:
    if family_name not in ['Disproportionation']:
        continue  # start here

    if family_name in ['Intra_R_Add_Endocyclic', 'Intra_R_Add_Exocyclic']:  # something wrong with these families, can't get map
        continue
    if family_name in ['1,3_sigmatropic_rearrangement']:  # available training reactions doesn't match tree, ambiguous mapping, should be retrained
        continue
    if database.kinetics.families[family_name].auto_generated:
        autogenerated_families.append(family_name)
        print(f'Getting reaction map for {family_name}...')
        reaction_maps[family_name] = database.kinetics.families[family_name].get_reaction_matches(
            thermo_database=database.thermo,
            remove_degeneracy=True,
            get_reverse=True,
            exact_matches_only=False,
            fix_labels=True
        )

        # we'll use the order of the training reactions in the 'Root' node to determine the order of the training reactions for the perturbations
        # all training reactions in the reaction_map will use the same reaction objects, no matter which node they appear in
        # this will be how we disambiguate duplicates. They'll have the same memory address in the training map


# 3. set parameters for fitting
Tref = 1000.0
fmax = 1.0e5

N = 2000  # ensemble size matches BEEF-vdW for now, but could be made bigger if needed
N = 100  # for testing

np.random.seed(400)

k_param_engine = rmgpy.tools.uncertainty.KineticParameterUncertainty()


# 3. fit the rules
for family_name in autogenerated_families:
    print(f'Fitting rules for {family_name}...')

    recipe = database.kinetics.families[family_name].forward_recipe.actions

    if len(reaction_maps[family_name]['Root']) != len(database.kinetics.families[family_name].depositories[0].entries):
        print(f"Warning: number of training reactions for {family_name} does not match number of entries in the training depository. This could be a problem. {len(reaction_maps[family_name]['Root'])} vs {len(database.kinetics.families[family_name].depositories[0].entries)}")
    # assert len(reaction_maps[family_name]['Root']) == len(database.kinetics.families[family_name].depositories[0].entries), "not sure how many training reactions there are"

    # make the ensemble matrix to hold results of the perturbations
    n_training_reactions = len(reaction_maps[family_name]['Root'])
    n_rules = len(database.kinetics.families[family_name].rules.entries)
    print(f'{n_training_reactions} training reactions, {n_rules} rules')
    ensemble_matrix = np.zeros((n_rules + n_training_reactions, N))
    original_values = np.zeros(n_rules + n_training_reactions)

    for i in range(len(reaction_maps[family_name]['Root'])):
        original_values[n_rules + i] = reaction_maps[family_name]['Root'][i].get_rate_coefficient(Tref)

    # come up with random perturbations for each training reaction
    # Delta ln k = 0.5 for a uniform distribution corresponds to a factor of exp(0.5 *sqrt(3)) = 2.377 kmax / k0

    # let's say we now have a normal distribution of these multipliers, and we want 95% of of the values to fall within that 2.377 bound,
    # For a normal distribution, 95% of the values fall between -1.96 and 1.96 standard deviations
    # This works out to std dev of sigma * sqrt(3) / 1.96 = 0.4414
    standard_deviation = k_param_engine.dlnk_training * np.sqrt(3) / 1.96

    perturbations = np.random.normal(loc=0.0, scale=standard_deviation, size=(n_training_reactions, N))

    # go through duplicate reactions and overwrite the perturbations to be the same for duplicates, since they will be represented by the same reaction object in the tree
    for i in range(n_training_reactions):
        for j in range(i + 1, n_training_reactions):
            if reaction_maps[family_name]['Root'][i].is_isomorphic(reaction_maps[family_name]['Root'][j]) and \
                    reaction_maps[family_name]['Root'][i].kinetics.is_similar_to(reaction_maps[family_name]['Root'][j].kinetics):
                perturbations[j, :] = perturbations[i, :]
                
    # now convert these from log-space to multipliers for the A factors
    perturbed_multipliers = np.exp(perturbations)

    # for now, loop through the nodes, then perturbations one at a time, but this could maybe be vectorized/parallelized in the future?
    node_index = 0
    for node_name, rate_rule in database.kinetics.families[family_name].rules.entries.items():

        # fit the rule and compare to existing kinetics
        rxns = reaction_maps[family_name][node_name]
        ranks = [r.rank for r in reaction_maps[family_name][node_name]]
        label = node_name
        A_originals = [x.kinetics.A.value_si for x in rxns]

        # ------------------------- parallel implementation -------------------------
        def _perturb_one(i):
            """
            Run _make_rule for a single perturbation index
            Returns (i, node_rate, training_rates)
            """
            training_rates = np.multiply(perturbed_multipliers[:, i], original_values[n_rules:])
            for j in range(len(rxns)):
                rxns[j].kinetics.A.value_si = perturbed_multipliers[j, i] * A_originals[j]
            rr = recipe, rxns, Tref, fmax, label, ranks
            new_kinetics = rmgpy.data.kinetics.family._make_rule(rr)
            return i, new_kinetics.get_rate_coefficient(Tref), training_rates


        # N_WORKERS = os.cpu_count() - 1 or 1
        N_WORKERS = 4
        with concurrent.futures.ProcessPoolExecutor(max_workers=N_WORKERS) as pool:
            for i, node_row, training_rows in pool.map(_perturb_one, range(N)):
                ensemble_matrix[node_index, i] = node_row
                ensemble_matrix[n_rules:, i] = training_rows

        # # --------------------------- serial implementation for reference ---------------------------
        # for i in range(N):
        #     ensemble_matrix[n_rules:, i] = np.multiply(perturbed_multipliers[:, i], original_values[n_rules:])

        #     # perturb the training reactions for this node according to the current perturbation
        #     for j in range(len(rxns)):
        #         rxns[j].kinetics.A.value_si = perturbed_multipliers[j, i] * A_originals[j]

        #     rr = recipe, rxns, Tref, fmax, label, ranks
        #     new_kinetics = rmgpy.data.kinetics.family._make_rule(rr)
        #     ensemble_matrix[node_index, i] = new_kinetics.get_rate_coefficient(Tref)

        # reset to original A factors
        for j in range(len(rxns)):
            rxns[j].kinetics.A.value_si = A_originals[j]
        rr = recipe, rxns, Tref, fmax, label, ranks
        original_kinetics = rmgpy.data.kinetics.family._make_rule(rr)
        original_values[node_index] = original_kinetics.get_rate_coefficient(Tref)

        node_index += 1

    # # make sure none of the original values are zero
    # for i in range(n_training_reactions):
    #     training_index = reaction_maps[family_name]['Root'][i].index
    #     if original_values[n_rules + training_index] == 0:
    #         print(f"Original value for training reaction {training_index} in {family_name} is zero, this will cause problems. Check the training reactions for this family.")
    # for i in range(n_rules):
    #     if original_values[i] == 0:
    #         print(f"Original value for node {i} in {family_name} is zero, this will cause problems. Check the training reactions for this family.")
    assert np.all(original_values != 0), "Some original values are zero, can't compute relative changes. This shouldn't happen, check the training reactions for this family."

    # for now, save the ensemble matrix too
    np.save(f'{family_name}_ensemble_matrix.npy', ensemble_matrix)

    # save the covariance matrix
    covariance_matrix = np.cov(ensemble_matrix)
    np.save(f'{family_name}_covariance_matrix.npy', covariance_matrix)

    # save the ordering of the training reactions in the reaction map 'Root', which corresponds to the ordering of the perturbations in the ensemble matrix
    with open(f'{family_name}_training_map.pkl', 'wb') as f:
        pickle.dump(reaction_maps[family_name]['Root'], f)


end_time = time.time()
elapsed_time = end_time - start_time
print(f'Total elapsed time: {elapsed_time:.2f} seconds')