# Script to compute covariance matrices for each of the BM tree nodes

import os
import copy
import re
import pickle
import numpy as np
import pandas as pd
import shutil
import glob
import subprocess

import rmgpy.data.thermo
import rmgpy.data.rmg
import rmgpy.chemkin

import rmgpy.tools.uncertainty

import matplotlib.pyplot as plt



# 1. load the database
# load the tree from the database
database = rmgpy.data.rmg.RMGDatabase()
database.load(
    path = rmgpy.settings['database.directory'],
    thermo_libraries = [
        'Klippenstein_Glarborg2016',
        'BurkeH2O2',
        'thermo_DFT_CCSDTF12_BAC', 
        'DFT_QCI_thermo',
        'primaryThermoLibrary',
        'primaryNS',
        'NitrogenCurran',
        'NOx2018',
        'FFCM1(-)',
        'SulfurLibrary',
        'SulfurGlarborgH2S',
        'SABIC_aromatics'
    ],
    transport_libraries = [],
    reaction_libraries = [],
    seed_mechanisms = [],
    kinetics_families = 'default',
    kinetics_depositories = ['training'],
    depository = False,
) 

for family in database.kinetics.families:
    if not database.kinetics.families[family].auto_generated:
        database.kinetics.families[family].add_rules_from_training(thermo_database=database.thermo)
        database.kinetics.families[family].fill_rules_by_averaging_up(verbose=True)

def get_i_thing(thing, thing_list):
    for i in range(len(thing_list)):
        if thing.is_isomorphic(thing_list[i]):
            return i
    assert False, f"Couldn't find {thing} in list of {thing_list}"

# 2. get the mapping of training reactions to tree nodes
autogenerated_families = []
reaction_maps = {}
for family_name in database.kinetics.families:
    if family_name in ['Intra_R_Add_Endocyclic', 'Intra_R_Add_Exocyclic']:  # something wrong with these families, can't get map
        continue
    if family_name in ['1,3_sigmatropic_rearrangement']:  # available training reactions doesn't match tree, ambiguous mapping, should be retrained
        continue
    if database.kinetics.families[family_name].auto_generated:
        autogenerated_families.append(family_name)
        print(f'Getting reaction map for {family_name}...')
        reaction_maps[family_name] = database.kinetics.families[family_name].get_reaction_matches(
            thermo_database=database.thermo,
            remove_degeneracy=True,
            get_reverse=True,
            exact_matches_only=False,
            fix_labels=True
        )

        training_reaction_items = [x.item for key, x in database.kinetics.families[family_name].depositories[0].entries.items()]
        training_reaction_data = [x.data for key, x in database.kinetics.families[family_name].depositories[0].entries.items()]

        # check if any training reactions are duplicates
        for i in range(len(training_reaction_items)):
            for j in range(i + 1, len(training_reaction_items)):
                if training_reaction_items[i].is_isomorphic(training_reaction_items[j]) and training_reaction_data[i].is_identical_to(training_reaction_data[j]):
                    print(f"Warning: training reactions {i} and {j} in {family_name} are isomorphic and identical. This could cause problems with the mapping. Check the training reactions for this family.")

        # assign index to each reaction for later use
        # this needs to be a 1:1 mapping
        for node_name, rxns in reaction_maps[family_name].items():
            for i, rxn in enumerate(rxns):
                i_train = get_i_thing(rxn, training_reaction_items)
                rxn.index = i_train

        # check we did this right - but only if you change the code above, since this is slow
        for node_name, rxns in reaction_maps[family_name].items():
            for rxn in rxns:
                assert rxn.is_isomorphic(training_reaction_items[rxn.index]), f"Isomorphism mismatch for {rxn} in {family_name}"


# 3. set parameters for fitting
Tref = 1000.0
fmax = 1.0e5

N = 2000  # ensemble size matches BEEF-vdW for now, but could be made bigger if needed
N = 10  # for testing

np.random.seed(400)

k_param_engine = rmgpy.tools.uncertainty.KineticParameterUncertainty()

# 3. fit the rules
for family_name in autogenerated_families:
    print(f'Fitting rules for {family_name}...')
    

    recipe = database.kinetics.families[family_name].forward_recipe.actions


    if len(reaction_maps[family_name]['Root']) != len(database.kinetics.families[family_name].depositories[0].entries):
        print(f"Warning: number of training reactions for {family_name} does not match number of entries in the training depository. This could be a problem. {len(reaction_maps[family_name]['Root'])} vs {len(database.kinetics.families[family_name].depositories[0].entries)}")
    # assert len(reaction_maps[family_name]['Root']) == len(database.kinetics.families[family_name].depositories[0].entries), "not sure how many training reactions there are"

    # make the ensemble matrix to hold results of the perturbations
    n_training_reactions = len(reaction_maps[family_name]['Root'])
    n_rules = len(database.kinetics.families[family_name].rules.entries)
    print(f'{n_training_reactions} training reactions, {n_rules} rules')
    ensemble_matrix = np.zeros((n_rules + n_training_reactions, N))
    original_values = np.zeros(n_rules + n_training_reactions)

    for i in range(len(reaction_maps[family_name]['Root'])):
        training_index = reaction_maps[family_name]['Root'][i].index
        original_values[n_rules + training_index] = reaction_maps[family_name]['Root'][i].get_rate_coefficient(Tref)

    # come up with random perturbations for each training reaction
    perturbations = np.random.normal(loc=0.0, scale=k_param_engine.dlnk_training, size=(n_training_reactions, N))

    # now convert these to multipliers for the A factors
    perturbed_multipliers = np.float_power(10, perturbations)

    # for now, loop through the nodes, then perturbations one at a time, but this could maybe be vectorized/parallelized in the future?
    node_index = 0
    for node_name, rate_rule in database.kinetics.families[family_name].rules.entries.items():

        # fit the rule and compare to existing kinetics
        rxns = reaction_maps[family_name][node_name]
        ranks = [r.rank for r in reaction_maps[family_name][node_name]]
        label = node_name
        A_originals = [x.kinetics.A.value_si for x in rxns]

        for i in range(N):
            # perturb the training reactions for this node according to the current perturbation
            for j in range(len(rxns)):
                rxns[j].kinetics.A.value_si = perturbed_multipliers[j, i] * A_originals[j]

            rr = recipe, rxns, Tref, fmax, label, ranks
            new_kinetics = rmgpy.data.kinetics.family._make_rule(rr)
            ensemble_matrix[node_index, i] = new_kinetics.get_rate_coefficient(Tref)


        # reset to original A factors
        for j in range(len(rxns)):
            rxns[j].kinetics.A.value_si = A_originals[j]
        rr = recipe, rxns, Tref, fmax, label, ranks
        original_kinetics = rmgpy.data.kinetics.family._make_rule(rr)
        original_values[node_index] = original_kinetics.get_rate_coefficient(Tref)

        node_index += 1

    # make sure none of the original values are zero
    for i in range(n_training_reactions):
        training_index = reaction_maps[family_name]['Root'][i].index
        if original_values[n_rules + training_index] == 0:
            print(f"Original value for training reaction {training_index} in {family_name} is zero, this will cause problems. Check the training reactions for this family.")
    for i in range(n_rules):
        if original_values[i] == 0:
            print(f"Original value for node {i} in {family_name} is zero, this will cause problems. Check the training reactions for this family.")
    
    assert np.all(original_values != 0), "Some original values are zero, can't compute relative changes. This shouldn't happen, check the training reactions for this family."







# not_close = 0
# # Get baseline for each node and make sure it's not too different from what's currently in the database
# for node_name, rate_rule in database.kinetics.families[family_name].rules.entries.items():
#     if not rate_rule[0].data.uncertainty.N == len(reaction_maps[node_name]):
#         print(node_name)

#     # fit the rule and compare to existing kinetics
#     rxns = reaction_maps[node_name]    
#     label = node_name
#     ranks = [r.rank for r in reaction_maps[node_name]]
#     rr = recipe, rxns, Tref, fmax, label, ranks

#     new_kinetics = rmgpy.data.kinetics.family._make_rule(rr)
# #     if not new_kinetics.is_similar_to(rate_rule[0].data):
#         # print(rate_rule)
#         not_close += 1
# print( not_close / len(database.kinetics.families[family_name].rules.entries))
        
#         # Ts = np.linspace(300, 1500, 101)
#         # new_ks = np.zeros_like(Ts)
#         # old_ks = np.zeros_like(Ts)
#         # delta_H = 0
#         # for i in range(len(Ts)):
#         #     new_ks[i] = new_kinetics.get_rate_coefficient(Ts[i], delta_H)
#         #     old_ks[i] = old_kinetics.get_rate_coefficient(Ts[i], delta_H)
            
        
#         # plt.plot(1.0 / Ts, np.log10(old_ks), label='old')
#         # plt.plot(1.0 / Ts, np.log10(new_ks), label='new')
#         # plt.show()

